### ISSUE TITLE
discussion: push capa library to pypi?

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#154]
putting capa on pypi would make it a lot easier for other projects to use its logic.

however, there are at least two concerns:
  1. rules are not packaged with the library, so users have to bring their own. i think this is ok.
  2. capa relies on vivisect, which is not on pypi.

(2) is the more interesting discussion. in [flare-floss](https://github.com/fireeye/flare-floss/) we avoided a release on pypi for this reason. but there was definitely strong interest in it. since the floss release, upstream vivisect isn't really any closer to being released on pypi.

should we push our vivisect fork to pypi as well as capa? if so, we can use our own package name, maybe `wivisect` :-D

**Comment by williballenthin** [comment]
ping @rakuy0 @atlas0fd00m for upstream vivisect perspective

**Comment by Ana06** [comment]
@williballenthin 
> rules are not packaged with the library, so users have to bring their own. i think this is ok.

couldn't we include the rules?

btw, this GitHubAction seems to make the automatic upload really easy: https://github.com/pypa/gh-action-pypi-publish

**Comment by rakuy0** [comment]
@williballenthin I'd like to apologize for the delay in getting vivisect up on pypi proper. At lot of other things have taken priority.

Personally, I would like to avoid any kind of naming collision since it generates confusion down the line. And to put my money where my mouth is: https://github.com/vivisect/vivisect/pull/292 (and test: `pip install -i https://test.pypi.org/simple/ vivisect`)

As for a py3 port, I'm already wading into those waters and directing more of my efforts towards that. I'll keep you in the loop on that.

**Comment by atlas0fd00m** [comment]
@williballenthin when we cut over to Py3, what are the coordination needs on your side?  are your projects ready to go when vivisect is completes the Py3 migration?

as for Pypi, as @rakuy0 stated, it's a priority and almost out the door.  thanks for tagging us into this conversation.

**Comment by williballenthin** [comment]
capa runs under py3 when using IDAPython as the backend, so this project is good to go.

floss will probably need some updates, and its do for a refresh soon, anyways. i'll be happy to volunteer this effort :-)

**Comment by williballenthin** [comment]
#175 might be sufficient here, need to test

**Comment by williballenthin** [comment]
sent the following email to the account associated with the PyPI project "capa" that I wonder might be @tranvinhthuy ?

![image](https://user-images.githubusercontent.com/156560/88214527-92f40080-cc17-11ea-8689-b5ceb46f9bdc.png)

in the meantime, i'll test using `flare-capa` project on PyPI.

**Comment by williballenthin** [comment]
nope, can't have a "direct dependency" URL specified in setup.py for viv:

![image](https://user-images.githubusercontent.com/156560/88215271-a2c01480-cc18-11ea-8c91-e11cf757b7a0.png)

**Comment by williballenthin** [comment]
so this does exist: https://pypi.org/project/flare-capa/ but hopefully one day we'll get https://pypi.org/project/capa/

**Comment by Ana06** [comment]
Direct dependencies don't work in PyPI. They do not want PyPI to reach URLs outside PyPI: https://github.com/pypa/pip/issues/5566#issuecomment-402417467

**Comment by williballenthin** [comment]
vivisect on pypi!?
https://pypi.org/project/vivisect/#history

**Comment by williballenthin** [comment]
request for transfer of the PyPI project name `capa`:

https://github.com/pypa/pypi-support/issues/984
