### ISSUE TITLE
regex matches only a single string per scope

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#159]
as noted in https://github.com/fireeye/capa/pull/155/files#r455331827, Regex will only match a single string in a given scope, because it does an early return with the match locations. for completeness, it should probably return all matching strings in a scope. this shouldn't change what rules match, but the results will be more thorough.

**Comment by williballenthin** [comment]
we'll have to update the vverbose renderer when we fix this, because the matches strings may be different (unless a number feature, where number=10 is always rendered the same way).

use 7204e3efc2434012e13ca939db0d0b02 as a testcase

**Comment by williballenthin** [comment]
this is going to change the result document, where a `regex` node will have a field `matches` instead of `match`.

**Comment by mr-tz** [comment]
Willi, can you please lead this one?
