### ISSUE TITLE
capa explorer rule generator support

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#163]
## Summary

Allow to write rules guided by IDA Pro's analysis. 

## Motivation

Easy rule writing from withing IDA.

## Additional context

If you want to help on this, we have some existing code to get started.

## Functionality

The following is a list of functionality to support (no specific order):

- [x] automatically lint generated rule as user edits
- [x] save generated rule to file
- [x] cache rules read from disk (depends on #317)
- [x] automatically parse and match generated rule as user edits
- [x] cache rule author
- [x] cache rule scope
- [x] add header comment to generated rules (helpful metric)
- [x] cache features extracted from a function (leads to more efficient processing for matching generated rule)

**Comment by mr-tz** [comment]
- [ ] option to display failed branches; show failing branches (highlighted accordingly) so rule developers can see what features exist/are missing in a function/sample.

**Comment by mike-hunhoff** [comment]
Beta version of the rule generator for `capa explorer` committed [here](https://github.com/fireeye/capa/tree/explorer/rule-generator).

`capa explorer` contains two tabs, one for program analysis and one for generating new rules. The interface currently looks like this:

![Screen Shot 2021-01-15 at 1 51 13 PM](https://user-images.githubusercontent.com/42192796/104777822-9f29c800-5739-11eb-820c-1635c686fcde.png)

To generate rules simply navigate to a valid function within the IDA disassembly view and click `Analyze`. `capa explorer` will then parse features from the function and display them on the left.

You can add features from the left to the tree editor on the lower-right by right-clicking a feature and selecting `Add feature` or using multi-select and right-click. You can then use the tree editor to quickly modify, reorder, and nest features and expressions that you have added. The tree editor supports drag-and-drop of features and expressions, double-clicking a feature to modify its text, and removing and nesting features and expressions by right-clicking. You may also use the tree editor to add descriptions by double-clicking in the `Description` column next to the feature or expression you wish to add a description and the rule generator will properly format the description in the preview window given the type of feature or expression.

The preview window in the upper left automatically reflects the most recent changes made in the tree editor. You can modify the contents of the preview window but keep in mind that only the text between `meta:` and `features:` is retained as you make changes in the tree editor. Changes made below `features:` will be lost the next time you make changes in the tree editor.

This is a work in progress, currently tested on `Windows` in `IDA 7.5` with `Python 3.7.8`.

**Comment by mr-tz** [comment]
tracking outstanding ideas/enhancements in #603
