### ISSUE TITLE
Automate submodule sync (rules)

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#18]
via GitHub Actions

Currently has to be done manually, see https://stackoverflow.com/questions/5828324/update-git-submodule-to-latest-commit-on-origin

```
<in capa base dir>
cd rules/
git checkout master
git pull origin master
cd ..
git add rules/
git commit
git push origin master
```

**Comment by williballenthin** [comment]
added in https://github.com/fireeye/capa-rules/commit/6fa768bbefffd1517b824208c183968dc16724f3
