### ISSUE TITLE
Alter summary screen font colour - unreadable in PowerShell

### ISSUE THREAD

**Issue by AdamUoNSec** [fireeye/capa#181]
This is a minor issue, but running the standalone exe through PowerShell results in a summary screen that's very hard to read. The blue is very close to the default PowerShell background.

Not an issue in CMD of course but PowerShell is the better environment, having replaced CMD as the default for years now.

![image](https://user-images.githubusercontent.com/68689334/88276218-939f9c00-ccd6-11ea-8594-65dfd18c7a19.png)

Needs to be highlighted to be read!
![image](https://user-images.githubusercontent.com/68689334/88276489-0741a900-ccd7-11ea-9c65-6aa9239f0b6e.png)

**Comment by Ana06** [comment]
capa is using the default blue configured in your terminal. It is IMO a PowerShell bug to use a default blue that is not readable with their default background color.

Most terminals give you an easy way to modify the default colors and include profiles in which all the default colors are readable in the default background color. For example iterm2:
![Screen Shot 2020-07-23 at 16 24 36](https://user-images.githubusercontent.com/16052290/88298383-5f8da080-cd01-11ea-8706-71b46a716dfe.png)

It seems that in Powershell changing the default colors is not that easy, but it can be done modyfing the registry: https://stackoverflow.com/questions/16280402/setting-powershell-colors-with-hex-values-in-profile-script Changing the background to white and the default text color to black, also produces a readable output:
![Screen Shot 2020-07-23 at 16 32 41](https://user-images.githubusercontent.com/16052290/88298990-2570ce80-cd02-11ea-92cd-35fcdb85656a.png)

But I understand that you may not want to change your terminal colors in that way to be able to read capa output. Maybe we should provide a `no-color` option in capa. 🤔

**Comment by AdamUoNSec** [comment]
That's a fair assessment, this isn't the first time I've run into the problem.

A no-color option sounds like a good idea from an accessibility standpoint, regardless.

**Comment by Ana06** [comment]
@AdamUoNSec 

> A no-color option sounds like a good idea from an accessibility standpoint, regardless.

I was expecting that it was easy to configure colors in all terminals, so that people needing an special configuration change it globally for all console applications. It may be that PowerShell is not the best option for accesibility... but still a `no-color` option may be a good idea.

**Comment by williballenthin** [comment]
you can use `capa --color=never` to disable output coloring, which is probably best in the ps1 terminal.

**Comment by Ana06** [comment]
Oh! we already have an option. 🙈 Then we can close this I guess...

**Comment by AdamUoNSec** [comment]
Good stuff, thanks Will - didn't spot that on the help page!
