### ISSUE TITLE
document release process

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#184]
documenting the release process here, and we can migrate to the docs once its finalized.

  0. ensure tests pass and linter --thorough works
  1. update [version.py](https://github.com/fireeye/capa/blob/master/capa/version.py)
  2. review changes
    a.  capa https://github.com/fireeye/capa/compare/v1.0.0...v1.0.1
    b.  capa-rules https://github.com/fireeye/capa-rules/compare/v1.0.0...v1.0.1
  3. update [CHANGELOG.txt](https://github.com/fireeye/capa/blob/master/CHANGELOG.txt)
    a. additions
    b. removals (major release only)
    c. deprecations
    d. breaking changes (major release only)
    e. changes
    f. fixes
  4. [create release in GH](https://github.com/fireeye/capa/releases) using text from changelog
  5. create tag in capa-rules matching release version
  6. verify GH actions upload artifacts upon completion

---

other stuff:
  7. bump FC svc image

**Comment by Ana06** [comment]
This will be useful: https://github.com/actions/create-release 😉

**Comment by williballenthin** [comment]
https://blog.yossarian.net/2020/11/05/Towards-an-automated-changelog-workflow

**Comment by Ana06** [comment]
What do you think about moving this issue to the [Wiki](https://docs.github.com/en/github/building-a-strong-community/about-wikis) (it needs to be enabled in the project settings)?

**Comment by mr-tz** [comment]
I'd prefer an issue template `new_release.md` with the above checklist. This could then be associated with each version milestone and contain a task list to check off.

**Comment by Ana06** [comment]
An issue template for the release process would be shown every time someone creates an issue. This may be confusing for some users. In addition, if we modify the release process, we need to update the template and the current milestone (duplication).

I personally think this should be part of the documentation instead of an issue/issue template. We could also add it to the docs folder. But I think the Wiki is used by quite some open source projects to document those kind of things. For example:
- [jquery](https://github.com/jquery/jquery/wiki/Release-process)
- [discord.js](https://github.com/discordjs/discord.js/wiki/Release-Checklist)
- [rr](https://github.com/rr-debugger/rr/wiki/Release-checklist)
- [open-build-service](https://github.com/openSUSE/open-build-service/wiki/OBS-Major-Release-HOWTO)

**Comment by williballenthin** [comment]
personal opinions, not decisions:

We should enable the wiki if we expect many other people to contribute to it; otherwise, I think we should stick to md formatted files embedded within the repo. They get rendered essentially the same within GH and .md documents keep our history within git (vs. GH webapp).

We should really have a release issue with checklist for each release (sorry, I've been lazy in the past, no more!). Whether we use an issue template (possibly prefix with `z-ignore-` or something) or a block that we copy-pasta from the docs, I don't really care.

The milestone tracks issues that should be included/resolved with a release; I don't think it should duplicate the information in the release issue. The release issue should be a checklist that reminds the releaser to, e.g., update `version.py`, run the linter, etc.

**Comment by Ana06** [comment]
@williballenthin 

> We should enable the wiki if we expect many other people to contribute to it; otherwise, I think we should stick to md formatted files embedded within the repo. They get rendered essentially the same within GH and .md documents keep our history within git (vs. GH webapp).

This sounds reasonable 👍  What about a `release.md` file in our doc folder? 

> We should really have a release issue with checklist for each release (sorry, I've been lazy in the past, no more!). Whether we use an issue template (possibly prefix with z-ignore- or something) or a block that we copy-pasta from the docs, I don't really care.
>
> The milestone tracks issues that should be included/resolved with a release; I don't think it should duplicate the information in the release issue. The release issue should be a checklist that reminds the releaser to, e.g., update version.py, run the linter, etc.

I am not sure if I understand how this should work. If I want to release, should I create an issue with the checklist and mark the items as I complete them? Why do we need an issue? The list is not that long. Isn't enough that the person releasing follows the list without creating an issue? 😕 Alternatively, it could be copied into the PR for the changelog. 🤔

**Comment by williballenthin** [comment]
> Alternatively, it could be copied into the PR for the changelog. 

even better, i think this is a good place to put the checklist.

the last the i want to do is create more process that is annoying to complete. so, lets definitely not make any bad decisions here. but, i know i keep forgetting steps during release, so i certainly want to refer to a list. putting it in the PR makes it clear which items i've completed, so i'll personally do this, but wont necessarily expect everyone else to (unless we agree).

**Comment by mr-tz** [comment]
My reasoning for an issue template was that we only have to update one file and can immediately use it (instead of copying it) when working on a new release. By task list I meant the release process steps such as:
- [ ] run tests
- [ ] update `setup.py`
- [ ] ...

Versus a numbered list as used above.

Using a PR template should also work. Those are also used by less people, although I don't think it's that confusing to users if we put an explanation in there that this is only meant for use by the core dev team.

**Comment by Ana06** [comment]
> > Alternatively, it could be copied into the PR for the changelog. 
> 
> even better, i think this is a good place to put the checklist.
> 
> the last the i want to do is create more process that is annoying to complete. so, lets definitely not make any bad decisions here. but, i know i keep forgetting steps during release, so i certainly want to refer to a list. putting it in the PR makes it clear which items i've completed, so i'll personally do this, but wont necessarily expect everyone else to (unless we agree).

I can do it like this as well! It may be also useful if more than one person take care of the release (to know what has been already done).

@mr-tz 
> Using a PR template should also work. Those are also used by less people, although I don't think it's that confusing to users if we put an explanation in there that this is only meant for use by the core dev team.

I think you can not have more than one PR template. One alternative would be to add it as a comment at the button. The other alternative is to have it in a `release.md` file in our doc folder and copy it to the PR when we release. 🤔 

What about I add a commit to https://github.com/fireeye/capa/pull/476 with a `release.md` file in our doc folder which documents the release process? We can decide to move it somewhere else afterwards. 🤔

**Comment by williballenthin** [comment]
> What about I add a commit to #476 with a release.md file in our doc folder which documents the release process

yeah, lets definitely start with that. and we can continue the discussion here if we have further ideas.
