### ISSUE TITLE
Do not print tqdm progress when -q, --quiet switch is used

### ISSUE THREAD

**Issue by jsmnsr** [fireeye/capa#193]
## Summary
Capa outputs tqdm updates even when the -q switch is used. This should probably be supressed.

## Motivation

The expectation of the -q switch is that there is no output to the shell upon execution of the command.

## Describe alternatives you've considered

It seems like you can quiet it by passing the right argument to tqdm, but that is not connected to the -q switch. It would be preferred if this was the case.

**Comment by williballenthin** [comment]
nice catch @jsmnsr thanks!
