### ISSUE TITLE
Should we add more badges?

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa#196]
### Summary
I think it would be useful/cool/beautiful to add some more badges. :bowtie: 

##### Downloads number

I don't know if you have realized but capa binaries have already been downloaded 1870 times. This deserves a badge! 🥳 

![image](https://img.shields.io/github/downloads/fireeye/capa/total)

It has also been cloned 720 times (although by only 292 unique cloners... I wonder who is cloning capa that many times and why 😆). But it seems like GitHub doesn't expose that number publicly: https://github.com/badges/shields/issues/1765 It could be updated with GitHub actions though...

##### Releases related
We could add this two badges related to the releases:

![image](https://user-images.githubusercontent.com/16052290/88395899-0d608400-cdc2-11ea-9460-dcef18b278bf.png)
![image](https://user-images.githubusercontent.com/16052290/88400387-9084d880-cdc8-11ea-936d-70c47820d92a.png)

They'll need an small update when releasing, which could be included in GitHub Actions. Related to https://github.com/fireeye/capa/issues/184

##### Coverage

![image](https://user-images.githubusercontent.com/16052290/88397520-544f7900-cdc4-11ea-940e-7879179ab809.png)

I am not sure how to deal with the fact that the IDA plugins are not tested. We don't want to have a very low percentage when capa's code have a good coverage. 🤔 

##### Maintained

Not sure if this is needed as you can see the commit history, but just an idea:
![image](https://user-images.githubusercontent.com/16052290/88400594-dc378200-cdc8-11ea-8e95-9a7566a69e6a.png)

### Motivation

I love badges!  ❤️ ![image](https://user-images.githubusercontent.com/16052290/88400550-cfb32980-cdc8-11ea-9a33-39941dbfeb8d.png) ❤️

**Comment by williballenthin** [comment]
> cloned 720 times

wonder if this is GH actions??

**Comment by williballenthin** [comment]
![image](https://user-images.githubusercontent.com/156560/88415453-c52e6b00-cd9b-11ea-94db-b2cc26e89472.png)

**Comment by Ana06** [comment]
@williballenthin 

> wonder if this is GH actions??

Yesterday there were ~30 runs in capa and ~20 in capa-rules. Taking into account that capa CI workflow checkouts the repo 3 times, this seems to be the case. :open_mouth: So we don't want a badge with the number of clones then. :rofl: we could still add the number of downloads which is really easy to add as it is built in in [shields](https://shields.io).

**Comment by re-fox** [comment]
> > cloned 720 times
> 
> wonder if this is GH actions??

I clone the repo multiple times per day (not 720 times though!) using a container based workflow -> https://github.com/re-fox/capa-docker.  Clones and rebuilds are cheap.  In many cases, it's just as easy to tear down the container and build a new one than maintain an existing repo.
