### ISSUE TITLE
remove characteristic(switch)?

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#231]
we currently support a feature `characteristic(switch)`; however, none of our rules use it. this alone is probably grounds enough to consider removing it. furthermore, switch analysis is not very easy, and i expect analysis results to differ across backends - leading to inconsistency.

can we remove this feature?

**Comment by mr-tz** [comment]
Yes, I'm fine with removing it. I think we had something in mind for it that didn't work out.
