### ISSUE TITLE
Control viv.json creation

### ISSUE THREAD

**Issue by weslambert** [fireeye/capa#244]
When running the Linux version of Capa (may apply to all versions), a `viv.json` file is copied to the running user's home directory (`$HOME/.viv/viv.json
`).  Is there a way to control where this file is copied, or to disable its creation on the host?

**Comment by williballenthin** [comment]
huh, i never noticed this. looks like a configuration file used to tweak [vivisect](https://github.com/vivisect/vivisect)'s default behavior.

it doesn't look like vivisect provides a way to configure this behavior: https://github.com/vivisect/vivisect/blob/da818a84e68876e625dca07550457df029a2b4ad/vivisect/__init__.py#L78
while there might be a way to reach in an patch the workspace to avoid saving the config, this sounds pretty brittle. let me open an issue against vivisect and see if they'll provide a mechanism for this.

**Comment by williballenthin** [comment]
this is fixed upstream.

we have some outstanding work to do to use the official vivisect available on pypi, so i'll likely bundle together these fixes.

**Comment by williballenthin** [comment]
closed in 09da1d1af0032ef80c38e841f43362a764a57301 with the bump to viv 0.1.0

thanks @rakuy0!
