### ISSUE TITLE
capa may report incorrect string reference for address matched by regex

### ISSUE THREAD

**Issue by mike-hunhoff** [fireeye/capa#262]
`capa` may report the wrong string reference for an address matched by a regex. May be related to #159.

For example, the string `http://practicalmalwareanalysis.com` reported in the following rule match is incorrect:

```
...
send HTTP request
namespace  communication/http/client
author     moritz.raabe@fireeye.com
scope      function
examples   BFB9B5391A13D0AFD787E87AB90F14F5:0x13145D60, 6A352C3E55E8AE5ED39DC1BE7FB964B1:0x100026E0
function @ 0x4021B0
  or:
    and:
      match: send data on socket @ 0x4021B0
        or:
          api: ws2_32.send @ 0x40231B
      string: http://www.practicalmalwareanalysis.com @ 0x4022C4
...
```

and should be ` HTTP/1.0\r\n\r\n` according to IDA:

![Capture98765](https://user-images.githubusercontent.com/42192796/91604523-07fbd980-e92c-11ea-85cf-6e648e65cf08.PNG)

Seen in `Practical Malware Analysis Lab 16-01.exe_:0x4021B0`.

**Comment by williballenthin** [comment]
output from `show-features`: 
![image](https://user-images.githubusercontent.com/156560/91770754-f4a47480-eb9e-11ea-9777-9ce4618a0a81.png)

**Comment by williballenthin** [comment]
reproduced on master:
![image](https://user-images.githubusercontent.com/156560/91770809-1b62ab00-eb9f-11ea-8873-c2fce694b20f.png)

`python -m capa.main tests/data/Practical\ Malware\ Analysis\ Lab\ 16-01.exe_ -t "send HTTP request" -vv`

**Comment by williballenthin** [comment]
added tests for the expected behavior and oddly enough they pass:
![image](https://user-images.githubusercontent.com/156560/91771394-2a962880-eba0-11ea-974e-ebb76f104a77.png)

wonder if maybe the results reporting has a bug.

**Comment by williballenthin** [comment]
the source of the bug is found here: https://github.com/fireeye/capa/blob/d3dad3a66ade6e74fbd2d75cdb2df7099741eeaf/capa/features/__init__.py#L154-L155

when we find a matching string, we assign this on the singular `Regex` instance and wrap it into a `Result`. obviously, if the regex matches multiple times, then the previous matches get overwritten. that's not good.
