### ISSUE TITLE
explorer: detect program rebase

### ISSUE THREAD

**Issue by mike-hunhoff** [fireeye/capa#267]
The goal here would be to detect and handle a program rebase that happens after the plugin has performed its analysis. Following a rebase the plugin should update accordingly so the addresses for rule/feature matches are accurate (re-run capa analysis is probably most straightforward solution).

Quick solution may be hooking `RebaseProgram` IDA UI event (see `<ida_install>\cfg\idagui.cfg`).

**Comment by williballenthin** [comment]
from an initial scan, i dont see an IDA callback for the "rebase program" event. but, might be able to use `ida_idp.IDB_Hooks.segm_start_changed`?

**Comment by williballenthin** [comment]
oh, i see what you're suggesting: to use `idaapi.UI_Hooks` and register a `RebaseProgram` event handler
