### ISSUE TITLE
use gitter.im for capa-related chat?

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#271]
we try to keep as much discussion as possible on github (issues) so that there's a public record of ideas. occasionally, there are discussions around capa development that might be better done via instant message. among the contributors from FEYE, we use our corporate instant messaging application to coordinate work. as we gather contributors outside of FEYE, then maybe we should consider something to fill this gap.

gitter.im is a website for realtime chat that caters towards projects hosted on github. we should consider adopting this platform when its necessary to use a public instant messaging platform.

(this issue is intended to be more of a discussion around the idea. i'm not 100% sure this feature is needed yet. interested to know what people think.)

**Comment by williballenthin** [comment]
placeholder gitter room: https://gitter.im/flare-capa/community

**Comment by williballenthin** [comment]
or maybe just use twitter or email or ... ?

**Comment by williballenthin** [comment]
im not sure that the overhead of setting this up, documenting it, and keeping an eye on the conversations is worth it quite yet, but something to keep in mind.

**Comment by mr-tz** [comment]
I feel like GitHub works well for now. If demand for it increases a chat is a good idea though.

**Comment by williballenthin** [comment]
i think i agree completely. lets reopen this issue in the future if we want to reconsider.
