### ISSUE TITLE
pip installation and IDA plugin instructions fail to install properly

### ISSUE THREAD

**Issue by adamprescott91** [fireeye/capa#293]
### Description

Following the instructions on the installation and usage pages I used pip to install the prerequisite packages and then used the `pip install https://github.com/fireeye/capa/archive/master.zip` command to install capa. This succeeded and capa can then be imported in Python.
Then opening IDA and attempting to run `main.py` via run script errors with message
`OSError: rule path C:/Users...../site-packages/capa\..\rules does not exist or cannot be accessed`

Similarly attempting to copy the IDA plugin into the IDA directory and running the plugin results in another error - 
```
C:\Program Files\IDA Pro 7.5\plugins\capa_plugin_ida.py: string argument without an encoding
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.5\python\3\ida_idaapi.py", line 604, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.5/plugins/capa_plugin_ida.py", line 9, in <module>
    from capa.ida.plugin import CapaExplorerPlugin
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\capa\ida\plugin\__init__.py", line 15, in <module>
    from capa.ida.plugin.form import CapaExplorerForm
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\capa\ida\plugin\form.py", line 15, in <module>
    import ida_settings
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\ida_settings-1.0.1-py3.8.egg\ida_settings\__init__.py", line 1, in <module>
    from .ida_settings import IDASettings, PermissionError
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\ida_settings-1.0.1-py3.8.egg\ida_settings\ida_settings.py", line 859, in <module>
    VALUE_1 = bytes("hello")
TypeError: string argument without an encoding
```

I'm presuming that there should be a step of creating a rules folder in the python site-packages folder or have an existing default one present. Or that there should be a prompt for a rules folder location that is currently not being displayed?

The IDA plugin issue looks more like a python warning due to IDA7.5 and python 3.8.5 being stricter on syntax/type warnings?

### Versions
capa 1.2.0
Python 3.8.5
IDA 7.5
Windows 10 Pro

**Comment by williballenthin** [comment]
hey @adamprescott91 thanks for reporting these issues.

The second issue, when you try to invoke the IDA plugin, is a duplicate of #289 thanks to some changes we made on master late last week. I'm going to work on addressing this right now, and will update this ticket.

The first issue is reasonable, and seems to come for our documentation being unclear. Essentially, when you `pip install` capa directly from the github archive URL, it doesn't include the rules submodule. Given that most (all?) users expect the rules to be present, we should definitely add some warning text around this documentation and maybe discourage it.

If you have a little more patience, would you consider trying "Method 3" of the installation instructions? Also, please continue to be vocal about sharing the things that don't make sense - then we can make the instructions easier for everyone.

**Comment by williballenthin** [comment]
I've updated the ida-settings dependency so that it should now work on all platforms. At your convenience, would you try to update capa and confirm that the plugin works now?

**Comment by adamprescott91** [comment]
Thanks @williballenthin 
I started from scratch with Method 3 and it all works smoothly now.
Having the Note in method 2 also clears up where I was misunderstanding the IDA installation as well.
