### ISSUE TITLE
`ida_settings` not compatible with Python 2.7

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#297]
### Description
Error in dependent library, but tracking here for awareness.

```python
...
    import ida_settings
  File "C:\Python27\lib\site-packages\ida_settings\__init__.py", line 1, in <module>
    from .ida_settings import IDASettings, PermissionError
  File "C:\Python27\lib\site-packages\ida_settings\ida_settings.py", line 174
    class IDASettingsInterface(metaclass=abc.ABCMeta):
                                        ^
SyntaxError: invalid syntax
```

Fix with:
```python
@six.add_metaclass(abc.ABCMeta)
class IDASettingsInterface():
```
via https://stackoverflow.com/questions/35673474/using-abc-abcmeta-in-a-way-it-is-compatible-both-with-python-2-7-and-python-3-5

### Steps to Reproduce

Setup IDA plugin and open IDA that uses Python 2.7.

**Actual behavior:**

Error when loading `ida-settings`

### Versions

IDA with Python 2.7

**Comment by mr-tz** [comment]
Another issue when changing the rules path:
```python
Traceback (most recent call last):
  File "capa\capa\ida\plugin\form.py", line 571, in change_rules_dir
    
  File "C:\Python27\lib\site-packages\ida_settings\ida_settings.py", line 257, in __setitem__
    return self.set_value(key, value)
  File "C:\Python27\lib\site-packages\ida_settings\ida_settings.py", line 412, in set_value
    raise TypeError("value cannot be bytes")
TypeError: value cannot be bytes
```

**Comment by williballenthin** [comment]
@mr-tz  @mike-hunhoff i've added you both as collaborators to ida-settings.

**Comment by williballenthin** [comment]
i *think* i've fixed the metaclass thing here: https://github.com/williballenthin/ida-settings/commit/4d569acd1c1fd69f9013947d22c856da801ae804

but i can't be sure on 2.7 since i don't have idapython 2.7 installed.

**Comment by williballenthin** [comment]
@mr-tz i dont see a line 571 in `ida/plugin/form.py`:

![image](https://user-images.githubusercontent.com/156560/92625607-1cbe6280-f286-11ea-8ef3-2dc0a74be423.png)

in any case, i think i see what's happened:

under py2.7
![image](https://user-images.githubusercontent.com/156560/92625744-4c6d6a80-f286-11ea-8ec2-2cafaa1332aa.png)

i didn't realize this was thing. fixing now.

**Comment by williballenthin** [comment]
in theory this should be fixed in https://github.com/fireeye/capa/commit/8cd90e5c2d49ad11aba52b643bb8b33912e4b073 by bumping ida-settings to v2.1.0

when you have a moment, can someone verify on 2.7?

**Comment by mike-hunhoff** [comment]
Looks like the version bump is working for me!

```
Python>import sys
Python>sys.version
'2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]'
Python>import pkg_resources
Python>pkg_resources.get_distribution("ida_settings").version
'2.1.0'
```
![Screen Shot 2020-09-09 at 10 44 55 AM](https://user-images.githubusercontent.com/42192796/92628117-8ee47680-f289-11ea-98ee-e2f24477769c.png)

**Comment by mike-hunhoff** [comment]
And looks like Python 3 is also happy.

```
Python>import sys
Python>sys.version
'3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]'
Python>import pkg_resources
Python>pkg_resources.get_distribution("ida_settings").version
'2.1.0'
```
