### ISSUE TITLE
Fail to load rules with IDA plugin after uninstalling and reinstalling capa

### ISSUE THREAD

**Issue by adamprescott91** [fireeye/capa#298]
### Description

Installing capa using Method 3 and then using the IDA plugin the first time works correctly.
I then uninstalled the capa module and reinstalled it in a different directory using the same method.
Subsequently every time the plugin is run in IDA it displays the error message

`Failed to load rules from C:/prev/dir. Please refer to IDA Output window for more information`

I believe this is due to the ida-netnode storage of the IDASettings in the "capa" node remembering the old directory even after removing the old capa installation.

It would be better if instead of the error message that the rules cannot be loaded, that the plugin prompts the user for a new rules folder or checks to see if the default rules location matches the currently saved rules location.

I briefly attempted to delete the "rule_path" dictionary element using the IDASettings module inside IDAPython with the "del_value" method but this resulted in an `ida_settings.PermissionError`.

Would it be better to save the IDASettings data into a file in either the Python directory for ida_settings or in the capa installation folder so that on an uninstall the path is cleared and then fresh installs won't be affected by old settings?

### Versions
IDA 7.5
Python 3.8.5
Capa 1.2.0
Windows 10 Pro

**Comment by williballenthin** [comment]
good suggestion, i like this

**Comment by williballenthin** [comment]
@mike-hunhoff assigning to you since i'll be out soon.

**Comment by mike-hunhoff** [comment]
Thank you for pointing this out! For now, you can change the rules directory from the plugin menu `Rules > Change rules directory...`.

![change_rule_dir](https://user-images.githubusercontent.com/42192796/92619233-7d49a180-f27e-11ea-8dd1-ca6592f03d88.PNG)
