### ISSUE TITLE
Capa explorer rule folder selection

### ISSUE THREAD

**Issue by stevemk14ebr** [fireeye/capa#309]
When using the plugin for the first time it asks to select a folder when you press analyze. It's not obvious this is supposed to be the rule folder and if the wrong folder is selected an error about rules not being loaded will be shown. Worse more the reset button will not work and future attempts to select analyze will not re-prompt the folder selection. This is not user friendly.

**Comment by stevemk14ebr** [comment]
In load_capa_results the try_catch needs to be a do_while loop where the settings are reset if a new path that works is provided.

**Comment by mike-hunhoff** [comment]
Thank you for reporting this @stevemk14ebr, we will get this fixed. For now, you can select a new rules directory by navigating to `Rules > Change rules directory...` in the plugin.
