### ISSUE TITLE
linter should enforce rule formatting

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#313]
the linter should check the formatting of each rule and emit a warning when the style is incorrect. 

I'm surprised it doesn't already but I ran into some rules yesterday that weren't formatted correctly, despite our linter being run regularly.

**Comment by mr-tz** [comment]
Is this meant for things like whitespace, indents, line-separators, single empty line at EOF?

**Comment by williballenthin** [comment]
yeah. we should be able to programmatically invoke the formatter, and compare the results with existing rule text.
