### ISSUE TITLE
error when target file contains Chinese characters

### ISSUE THREAD

**Issue by ihacku** [fireeye/capa#328]
```
./capa ../temp/一202009253623543164364364534.exe 
loading : 100%|██████████████████████████████████████████████████████████████████████████████████████| 345/345 [00:02<00:00, 160.84     rules/s]
matching: 100%|█████████████████████████████████████████████████████████████████████████████████████| 1592/1592 [00:28<00:00, 54.95 functions/s]
Traceback (most recent call last):
  File "capa/main.py", line 675, in <module>
  File "capa/main.py", line 610, in main
  File "capa/render/__init__.py", line 245, in render_default
  File "capa/render/default.py", line 167, in render_default
  File "capa/render/default.py", line 35, in render_meta
  File "site-packages/tabulate.py", line 1450, in tabulate
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 8: ordinal not in range(128)
```

capa version : capa-v1.3.0-macos

After remove Chinese characters, it works as usual.

**Comment by williballenthin** [comment]
1. can you share the sample file?

2. can you share where these characters are found?

**Comment by ihacku** [comment]
1. Sorry I can't share the sample file, but maybe you can download form vt.
https://www.virustotal.com/gui/file/c759a6280b62395d22edd40eecd32202ffce6e32de1c5c9596a184c0641bb570/detection
2. Just some random Chinese characters, it doesn't have to be specific character.

**Comment by ihacku** [comment]
Sorry I just realized that I didn't write the issue detailed enough, it's the file name that contains Chinese characters lead to the error.

**Comment by williballenthin** [comment]
thanks! that should be enough to enable us to reproduce the issue
