### ISSUE TITLE
FR: Indirect jmps as calls

### ISSUE THREAD

**Issue by re-fox** [fireeye/capa#337]
### Summary
In a sample within the testfiles repo `b87e9dd18a5533a09d3e48a7a1efbcf6` at offset `0x140007461` a `jmp` is issued rather than a `call`.  Causing the API not to be recognized by the feature extractor.

The function in Ghidra:

![image](https://user-images.githubusercontent.com/57954766/95115977-557e1a00-0714-11eb-8743-4df631e3f8be.png)

The small snippet of features extracted from that address
```
insn: 0x140007461: bytes(80 30 02 00 00 00 00 00 94 30 02 00 00 00 00 00 B0 30 02 00 00 00 00 00 CA 30 02 00 00 00 00 00 E0 30 02 00 00 00 00 00 F6 30 02 00 00 00 00 00 10 31 02 00 00 00 00 00 26 31 02 00 00 00 00 00 3A 31 02 00 00 00 00 00 4C 31 02 00 00 00 00 00 60 31 02 00 00 00 00 00 6E 31 02 00 00 00 00 00 80 31 02 00 00 00 00 00 A8 31 02 00 00 00 00 00 B4 31 02 00 00 00 00 00 C2 31 02 00 00 00 00 00 D0 31 02 00 00 00 00 00 DA 31 02 00 00 00 00 00 EC 31 02 00 00 00 00 00 04 32 02 00 00 00 00 00 1C 32 02 00 00 00 00 00 34 32 02 00 00 00 00 00 42 32 02 00 00 00 00 00 58 32 02 00 00 00 00 00 68 32 02 00 00 00 00 00 74 32 02 00 00 00 00 00 8A 32 02 00 00 00 00 00 A0 32 02 00 00 00 00 00 B6 32 02 00 00 00 00 00 C0 32 02 00 00 00 00 00 D0 32 02 00 00 00 00 00 DE 32 02 00 00 00 00 00)
insn: 0x140007461: mnemonic(jmp)
insn: 0x140007461: characteristic(cross section flow)
```

### Motivation
To ensure API are caught by the feature extractor

### Describe alternatives you've considered
I haven't consider any additional alternatives.

I'm unsure if patching this issue will lead to unexpected behaviour.   

## Additional context
I think the expected outcome would be for the API to be recognized and for the JMP instruction to be preserved in the extracted features.

**Comment by mr-tz** [comment]
Agreed, we should be able to extract the `api` feature in such cases.

As a heads up this is part of the `__raise_securityfailure` library function in the above example.
