### ISSUE TITLE
error: capa failed to load some rules

### ISSUE THREAD

**Issue by r0ny123** [fireeye/capa#339]
### Description
Capa fails to load some rules, which have "**description**" (introduced in  https://github.com/fireeye/capa-rules/pull/137) as a statement and reports those as invalid rules.

**Expected behavior:**
Capa should load the rules correctly.

**Actual behavior:**
Capa throws an error like the following
```
C:\Users\rony>capa --version
capa 1.3.0

C:\Users\rony>
C:\Users\rony>
C:\Users\rony>
C:\Users\rony>capa C:\Users\rony\Desktop\02179f3ba93663074740b5c0d283bae2.exe_
loading :   3%|##                                                             | 12/368 [00:00<00:07, 47.24     rules/s]
ERROR:capa:invalid rule: c:\python27-x64\lib\site-packages\capa\..\rules\anti-analysis\anti-debugging\debugger-detection\check-for-trap-flag-exception.yml: invalid rule: unexpected statement: description

C:\Users\rony>
```
#### Versions
capa 1.3.0

**Comment by mr-tz** [comment]
Thanks for reporting! Are you using the stand-alone version?
We need to cut a new release of it, soon.

**Comment by r0ny123** [comment]
I checked both stand-alone and capa as python library.

**Comment by mr-tz** [comment]
Right, stand-alone and the pip package result in that error.
As a workaround you can run capa from source, see https://github.com/fireeye/capa/blob/master/doc/installation.md#method-3-inspecting-the-capa-source-code or comment out the `- description` lines.
Sorry for the inconvenience!

**Comment by r0ny123** [comment]
no problem :) and yeah I was going to that, thanks!

**Comment by williballenthin** [comment]
sounds like we'd better get 1.4 out!

**Comment by mr-tz** [comment]
fixed in newest release, https://github.com/fireeye/capa/releases/tag/v1.4.0
