### ISSUE TITLE
or: optional: ... always matches, is this expected?

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#348]
In https://github.com/fireeye/capa-rules/blob/master/host-interaction/console/manipulate-console.yml we have the following logic:

![image](https://user-images.githubusercontent.com/156560/96743624-7041c700-1381-11eb-8518-5206e948ec59.png)

but this appears to match every function, probably because the `optional: ...` always evaluates to true, even if the other elements are not present.

couple options:
  - fix the rule to be `and( or(...), optional(...))`
  - fix the rule engine to ignore `optional` under `or`
  - update the linter to warn on this construct

**Comment by mr-tz** [comment]
I vaguely remember something similar a while back. Option 2 or 3 sound good so we don't burden the user to know of this.
