### ISSUE TITLE
Small bug in string extraction 

### ISSUE THREAD

**Issue by re-fox** [fireeye/capa#353]
### Description
Small bug in string extraction causing last character to be missed (example is utf-16).

### Steps to Reproduce
1. Open `773290480d5445f11d3dc1b800728966.exe_` (currently in PR in `capa-testfiles`)
2. `scripts/show-features.py 773290480d5445f11d3dc1b800728966.exe_ -F 0x140001140 `
3. Search for the string `%s:\\OfficePackagesForWDA` 

**Expected behavior:**
Full string is `%s:\\OfficePackagesForWDAG`

**Actual behavior:**
String is truncated

### Versions
Built from `master`

### Additional Information
It appears that this happens with other strings as well

```
insn: 0x1400011a7: string(WDAGUtilityAccoun)
insn: 0x140001231: string(CExecSvc.ex)
```

**Comment by mike-hunhoff** [comment]
Thank you for finding this @re-fox!

I confirmed this bug is limited to the viv extractor and addressed the issue in #364.
