### ISSUE TITLE
Missing binary compilation instructions

### ISSUE THREAD

**Issue by jg777** [fireeye/capa#357]
### Description

Missing binary compilation instructions for capa. Looking for "Method 3: Compiling on the command line without pip" in the Installation.md

### Steps to Reproduce

1. Open doc/installation.md
2. It does not contain binary build instructions without using pip at all.

**Expected behavior:**

Since the project is able to provide binary builds, then I would expect some build documentation so that users can compile their own binaries.

**Actual behavior:**

It is not clear how to compile your own capa binary.

### Versions
N/A

### Additional Information
N/A

**Comment by williballenthin** [comment]
take a peek at the CI configuration in the .github directory. basically, it boils down to invoking PyInstaller with the config also found in the .github directory.

**Comment by jg777** [comment]
I run `sudo pyinstaller setup.py` in the root directory. It then appears to "build". When I look through the results I can't find the capa binary. I'm sure I'm missing something here.

**Comment by williballenthin** [comment]
you shouldn't need to use sudo.

pyinstaller should be invoked against the spec file, not setup.py. 

the resulting binary ends up in build/ or dist/ (I don't recall off the top of my head)

**Comment by mr-tz** [comment]
Were you able to get it running? The command is: `pyinstaller .github/pyinstaller/pyinstaller.spec` and the compiled binary will be located in `dist/`.
