### ISSUE TITLE
JSON mode has spurious prints in Python 3

### ISSUE THREAD

**Issue by jcrussell** [fireeye/capa#368]
### Description

When running CAPA in JSON mode (`-j`) on a file and redirecting the output to a file, the output contains spurious lines that make the output not valid JSON.

### Steps to Reproduce

1. `capa -j <file> > out.json`
2. `python -m json.tool out.json`

**Expected behavior:**

Pretty printed JSON.

**Actual behavior:**

Invalid JSON. The first three lines are:

```
 is not an ELF
 is not an ELF
 is not an ELF
```

I think these are from the lief dependency (from SMDA):

https://github.com/lief-project/LIEF/blob/b49786fd039a1cf5173d5e6d02a36481aa730a47/src/ELF/Parser.cpp#L158

### Versions

```
# capa --version
capa 1.4.0
```
I just built from master (50d55f) so the version string appears wrong.

### Additional Information

I think we just need to make sure that `LIEF_ERR` goes to stderr and not stdout.

**Comment by jcrussell** [comment]
Adding `lief.logging.disable()` after `import lief` in `capa/features/extractors/smda/file.py` appears to fix it. I'm not finding a way to specify where lief logs.

**Comment by jcrussell** [comment]
But `lief.logging` is only available through the nightly builds.

**Comment by williballenthin** [comment]
ah yeah i think you're right about LIEF

looks like its configured to use STDOUT for logging messages:
https://github.com/lief-project/LIEF/blob/1364f22c78475caaa2d6b7cbe01f74e87cf44c34/src/logging.cpp#L37

**Comment by williballenthin** [comment]
im used to logging messages being printed to STDERR, but maybe thats a personal preference. do you think this is something we should report upstream?

**Comment by jcrussell** [comment]
Yeah, it seems like something to report upstream. Disabling logging works for now.

**Comment by mr-tz** [comment]
Does this issue still persist after the upstream LIEF update?

**Comment by jcrussell** [comment]
Fixed when using LIEF master. There's no tagged release yet though so users will encounter this unless they are also using LIEF master.

**Comment by williballenthin** [comment]
LIEF 0.11 released yesterday, so we can update and pin the dep

**Comment by williballenthin** [comment]
https://github.com/danielplohmann/smda/pull/19
