### ISSUE TITLE
IDA helper - detecting unicode strings api

### ISSUE THREAD

**Issue by steven-hh-ding** [fireeye/capa#387]
Hello! 

https://github.com/fireeye/capa/blob/5323f2fc312dd0d3ce654b18a875a1da6516176c/capa/features/extractors/ida/helpers.py#L176-L190

I found that maybe the API below is a bit more convenient, per their docs suggested. 

```python

strs = Strings()

# include & analyze all supported string types
strs.setup(strtypes=[i for i in range(11)])
strs = {v.ea:v for v in strs}

def find_string_at(ea, min=4):
    return strs[ea] if strs[ea].length >= min else ""

```
Would we be missing anything. Thanks!

**Comment by mr-tz** [comment]
That looks neat, thanks! We will check this out with @mike-hunhoff

**Comment by mike-hunhoff** [comment]
Hi @steven-hh-ding! Thank you for your suggestion! I originally used the `Strings` helper class and found it missed strings that the current implementation does not.

e.g. `mimikatz.exe_:0x4129F1` references the string `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789` in a tight loop from the following basic block:

![example_1](https://user-images.githubusercontent.com/42192796/103367501-81463d00-4a82-11eb-9dc7-d08f96df8405.PNG)

The initial analysis performed by IDA creates a byte at location `0x4B8800`:

![example_2](https://user-images.githubusercontent.com/42192796/103367591-c10d2480-4a82-11eb-9a40-d5b653454ec9.PNG)

This causes the `Strings` helper class (which IIRC relies on the analysis performed by IDA) to miss the string reference whereas the current implementation does not.

Example code:

```python
import idautils
import capa.features.extractors.ida.helpers

ea = 0x4B8800

strs = idautils.Strings()
strs.setup(strtypes=[i for i in range(11)], minlen=4)
strs = {v.ea:v for v in strs}

print(f"Checking 0x{'%X' % ea}...")
print(f"Result idautils.Strings(): {strs.get(ea, '')}")
print(f"Result idaapi.get_strlit_contents(): {capa.features.extractors.ida.helpers.find_string_at(ea)}")
```

Example output:

```
Checking 0x4B8800...
Result idautils.Strings(): 
Result idaapi.get_strlit_contents(): abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
```

There may be some argument tweaking to `idautils.Strings()` that I'm not aware of that could improve its performance, but for now we will want to stick with the current implementation (while unfortunately less convenient).

**Comment by steven-hh-ding** [comment]
ah I see! This is great. Thanks a lot for looking into this! We didn't notice `get_strlit_contents` actually covers strings that is not in the database. We now use get_strlit_contents instead. A bit surprising that IDA missed this simple string..
