### ISSUE TITLE
add option to enable viewing library rules

### ISSUE THREAD

**Issue by mike-hunhoff** [fireeye/capa#389]
As the number of library rules increases it may be useful to allow a user to enable these rules to be displayed in the plugin UI.

**Comment by mr-tz** [comment]
I can see this being useful in the plugin and maybe even for the `-vv` mode.

All render modes appear to use `rutils.capability_rules` which omits `library` rules. So adjusting there should be straight-forward.

**Comment by mike-hunhoff** [comment]
I played around with this idea and, in practice, opting to display library rules tends to make the output less readable. Additionally some samples have many, many library rule hits which can overwhelm the UI. For now, I'm closing this issue as triaged. We can revisit in the future if needed.
