### ISSUE TITLE
Have file limitations and corresponding messages live in capa-rules

### ISSUE THREAD

**Issue by recvfrom** [fireeye/capa#390]
### Summary

Currently the list of which rules should show messages about file limitations lives in capa:

https://github.com/fireeye/capa/blob/47bf7b1325571d95cd670d8239d9e1596797e963/capa/main.py#L154-L191

Would it make sense for that list to live in capa-rules instead?

### Motivation

If a new rule is added to capa-rules that should trigger a new file limitation message, it currently requires a corresponding PR to capa and then the message wouldn't be visible until users update the version of capa they are using (which might occur independently from updating the rules)

### Describe alternatives you've considered

Maybe have the file limitation message dictionary live in a standalone YAML file in the root of capa-rules?

## Additional context

N/A

**Comment by mr-tz** [comment]
That's a great idea and I like your suggestion of using a capa rule instead.

For example we could use a `library` rule with a special namespace, e.g. `capa/file-limitations` and features like
```
features:
  - or:
    - match: executable/installer
    - match: runtime/dotnet
    - ...
```

Then simplify the code accordingly. Would you mind taking a stab at this? Otherwise, I can address it soon.

**Comment by mr-tz** [comment]
In a similar fashion we could add a warning around anti-analysis techniques, e.g. when encountering anti-disassembly techniques, obfuscated API calls, etc. These could clarify what output to expect from a sample.

**Comment by williballenthin** [comment]
we could add an additional field to the meta block to indicate "this is a limitation rule" and maybe its warning text (or maybe just reuse the description field)?

**Comment by recvfrom** [comment]
@mr-tz I'm still navigating my company's open source contribution approval system, so I'm not sure when I'd be able to get a PR for this in by. :( Sorry about that

**Comment by mr-tz** [comment]
No worries, @recvfrom 😄 We'll get to it soon.

**Comment by mr-tz** [comment]
if we reuse rules for this a `namespace` feature may be helpful

**Comment by williballenthin** [comment]
proposing namespace `internal/limitations/file`

**Comment by williballenthin** [comment]
also need to be sure we don't render `internal` namespace to results
