### ISSUE TITLE
stop tqdm module from creating daemon threads when instantiated with disable = False

### ISSUE THREAD

**Issue by mike-hunhoff** [fireeye/capa#410]
The following code snippets create daemon threads, which results in unnecessary, long running threads when calling this code from the IDA Pro plugin:

https://github.com/fireeye/capa/blob/bb7001f5f2ec02a28ed706435aea1d7e71291e8f/capa/main.py#L369

and

https://github.com/fireeye/capa/blob/bb7001f5f2ec02a28ed706435aea1d7e71291e8f/capa/main.py#L118

`tqdm` when instantiated creates a new [daemon thread](https://github.com/tqdm/tqdm#monitoring-thread-intervals-and-miniters) and unfortunately setting `disable` to `False` does not prevent this thread from being created, as one would expect.

For now we can manually set `monitor_interval` to `0` for the instantiated `tqdm` object when the intention is to disable `tqdm` progress altogether e.g. 

https://github.com/fireeye/capa/blob/bb7001f5f2ec02a28ed706435aea1d7e71291e8f/capa/ida/plugin/form.py#L531-L533

**Comment by williballenthin** [comment]
yikes, that's annoying!

what if we assign `tqdm.tqdm` to a local variable `pbar`, and if the progress bar is disabled, overwrite `pbar` with a fake object, like:

```py
pbar = tqdm.tqdm
if disable_progress:
    pbar = lambda s, *args, **kwargs: s

for f in pbar(list(extractor.get_functions()), disable=disable_progress, desc="matching", unit=" functions"):
    ...
```

**Comment by mike-hunhoff** [comment]
that works for me!
