### ISSUE TITLE
CI: check version before release

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#422]
We tend to forget updating `version.py` when releasing a new version. 

Let's add an Action to update it automatically or at least abort if version.py != tag.

See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release

Related: https://github.com/fireeye/capa/issues/184

**Comment by Ana06** [comment]
Do we necessarily need to do this for capa v1.6.1? With the [release documentation](https://github.com/fireeye/capa/blob/master/doc/release.md), I think now it is more difficult to forget this and I don't think it is a priority. 

I am changing this to the v2.0.0 milestone and assigning it to myself. Let me know if you are not ok with this.

**Comment by mr-tz** [comment]
Yes, that sounds good to me!

**Comment by mr-tz** [comment]
Will this be worth the effort or are we good with the release check list?

**Comment by mr-tz** [comment]
Let's rely on the release checklist and reopen this if it fails just one more time 😉
