### ISSUE TITLE
"is not an ELF" spurious prints from LIEF

### ISSUE THREAD

**Issue by mike-hunhoff** [fireeye/capa#427]
e.g. capa output (`Python 3`, w/ `smda` backend):

```
loading : 100%|██████████████████████████████████████████████████████████████████████████████████████| 458/458 [00:00<00:00, 1521.14     rules/s]
 \ analyzing program is not an ELF
| analyzing program is not an ELF
matching: 100%|████████████████████████████████████████████████████████████████████████████████████████| 180/180 [00:02<00:00, 64.79 functions/s]
```

This appears to be an issue with `LIEF` and has already been reported upstream: https://github.com/lief-project/LIEF/issues/541

We should watch for a fix and pin the `LIEF` dependency appropriately.

**Comment by mike-hunhoff** [comment]
just to clarify this is till an issue with the latest version of `lief`:

```
C:\Exclusions\capa>python -c "import sys, lief;print(f'{sys.version}\n{lief.__version__}')"
3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
0.11.0-f58605f
```

**Comment by williballenthin** [comment]
messages seem to come from here:
https://github.com/lief-project/LIEF/blob/6720ed2385a580988f748e79c46a3ef085053471/src/ELF/Parser.cpp#L158-L172

i haven't yet been able to trace down how `ELF::parse` gets called from `lief.parse` :-(

**Comment by farzonl** [comment]
Looks like capa uses lief.parse in  3 places line  67,75, & [92](https://github.com/fireeye/capa/blob/a813e219e6d3ef84eacfe0b22a017c6bfc227916/capa/features/extractors/smda/file.py#L92).
All 3 cases use the filePath parser. All the lief.parse entry points start in the abstract parser. Your call stack will look like 
https://github.com/lief-project/LIEF/blob/6720ed2385a580988f748e79c46a3ef085053471/api/python/Abstract/objects/pyParser.cpp#L74
https://github.com/lief-project/LIEF/blob/6720ed2385a580988f748e79c46a3ef085053471/src/Abstract/Parser.cpp#L62
https://github.com/lief-project/LIEF/blob/6720ed2385a580988f748e79c46a3ef085053471/src/ELF/Parser.cpp#L158

Without debugging I'm a little perplex how this could have happened as in Abstract parser we check `if (ELF::is_elf(filename))` and then in the elf parser we check  ` if (not is_elf(filename))`

from reading `is_elf`, I don't see an obvious  issue that could explain this behavior but this is where you will want to put a breakpoint: https://github.com/lief-project/LIEF/blob/6720ed2385a580988f748e79c46a3ef085053471/src/ELF/utils.cpp#L32

**Comment by mr-tz** [comment]
@mike-hunhoff can you check if this issue still exists?

**Comment by williballenthin** [comment]
i have not encountered this message recently when using the SMDA backend. lets reopen if we encounter it again.
