### ISSUE TITLE
migrate to py3

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#432]
once viv has a py3 release, then we can move the project completely over to py3.

this would enable things like type hinting, etc.

we'll need to update the pyinstaller config to distribute a py3 interpreter instead.

this is a breaking change, so it will be part of the v2.0 release.

**Comment by Ana06** [comment]
is this address by https://github.com/fireeye/capa/pull/480 or is this something else? 🤔

**Comment by mr-tz** [comment]
Yes!
