### ISSUE TITLE
function id

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#433]
use a function identification technology to recognize functions and associate with their name and other metadata (like source library).

let rules match on these names/metadata.

consider filtering out rule matches in well known library functions to reduce FPs (by default).

discussion: https://github.com/fireeye/capa/discussions/414

**Comment by williballenthin** [comment]
#431 using capa features to identify functions

**Comment by williballenthin** [comment]
#434 using vivisect vamp backend to identify functions

**Comment by williballenthin** [comment]
#435 using FLIRT to identify functions

**Comment by williballenthin** [comment]
having function id leads to changes in the following places:

1. an initial pass across all functions to match signatures.
  a.  add symbol name to function (and any local names)
  b. attach metadata to address indicating signature hit
2. during feature extraction, skip functions that have metadata attached to address and indicating library function
3. during feature extraction, inspect call targets, and if they're to a matched function, emit API feature with recovered name

question: do we assume all signature matches are library functions? 
initial take: seems simplest for now. some technologies (e.g. FLIRT) don't necessarily have associated library/category/metadata.

**Comment by williballenthin** [comment]
do underlying backends provide function id on their own? or do they provide the APIs that capa needs to do its own form of function id? i think its this second one. though maybe we should support both, so IDA can continue to mark lib functions?

to support underlying function id:
  - `has_function_id(va: int) -> bool`
  - `get_function_name(va: int) -> str`

to support FLIRT matching by capa:
  - `get_bytes(va: int, size: int) -> bytes`

**Comment by williballenthin** [comment]
how do we provide function names/symbols to the backends as they're extracting features?

**Comment by mr-tz** [comment]
+1 on supporting both to leverage backend's function ID plus capa's own ID on top.
We could change the extractor `get_functions` signature to support modifiers, e.g. `skip_libs`, like the current IDA helper function does.

**Comment by williballenthin** [comment]
this is closed in #446
