### ISSUE TITLE
avoid the large viv dependencies on py3

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#440]
![image](https://user-images.githubusercontent.com/156560/109200424-d2f70500-775d-11eb-9b47-fbc10bd09b5b.png)

these definitely need to be excluded from the pyinstaller builds. i wonder if there's a way we can avoid fetching them during installation, esp. on server OSes.

**Comment by williballenthin** [comment]
asked upstream to limit the gui dependencies to a specific profile.

https://github.com/vivisect/vivisect/issues/371

**Comment by mr-tz** [comment]
appears to be fixed

**Comment by williballenthin** [comment]
i agree its fixed in master, though need new viv pypi release.

**Comment by williballenthin** [comment]
this is fixed upstream
