### ISSUE TITLE
Release roadmap - capa versions - Python 2/3

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#444]
#421 adds Python 3 support using the vivisect backend. However, the code also still supports Python 2.

I propose a version 1.6 release (https://github.com/fireeye/capa/milestone/8) that will provide the final support for Python 2 in the compiled release binaries. If vivisect provides another Py2 release we could pin to `vivisect=0.2.1`. This would be desirable to address the issues mentioned in the above milestone, but shouldn't be a blocker.

With version 2.0 and beyond (https://github.com/fireeye/capa/milestone/3) we will be supporting Python 3 only. To do:
- [x] documentation
- [x] remove Py2/3 branches, e.g. `if sys.version_info >= (3, 0):` see #456 
- [x] development using Py3 only (local dev practices and in CI)

Which Python versions should we support? 3.7, 3.8, 3.9? vivisect is Py 3.6+, Py 3.6 only receives security updates until 2021-12.

**Comment by williballenthin** [comment]
supporting 3.6 for the next year (or until next major release after 201-12) seems fair. 3.6 has wide deployment and i think its the default distributed with debian stable.

we can do our dev in 3.8/3.9 but maintain some CI tests that ensure 3.6 works ok.

if there's a killer feature that makes us want to upgrade to a later version, that's fine too! we'll just give people a bit of warning and bump the major version again.

thoughts?

**Comment by mr-tz** [comment]
Wow, at least for web 3.6 is still the most popular (https://w3techs.com/technologies/details/pl-python/3)

![2021-03-02_17-33-16](https://user-images.githubusercontent.com/17606537/109681102-6c1e8500-7b7d-11eb-8981-7768a71e4320.png)

Also see https://dev.to/hugovk/python-version-share-over-time-6-1jb8

My only concern with 3.6 stems from the experiences with long testing run times, see #405. Of course, this may stem from a bug which we should track down.

**Comment by Ana06** [comment]
I agree with supporting Python 3.6+ at least until 3.6 stops receiving security updates.

**Comment by mr-tz** [comment]
See #480

**Comment by williballenthin** [comment]
closed in #480
