### ISSUE TITLE
vivisect 1.0.0 extracts less features than vivisect 0.1.0

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa#445]
`971e599e6e707349eccea2fd4c8e5f67.exe_` and `dc4dc746d8a14060fb5fc7edd4ef5282.exe_` extract less features in Python 3 (with vivisect 1.0.0 and 1.0.1) than with Python2 and vivisect 0.1.0 (not 0.2.0). From https://github.com/fireeye/capa/pull/421:
```
insn: py2(  841858) py3(  528575) 62.78% - 971e599e6e707349eccea2fd4c8e5f67.exe_
bb:   py2(   12149) py3(    7498) 61.71% - 971e599e6e707349eccea2fd4c8e5f67.exe_
insn: py2(    4694) py3(    3133) 66.74% - dc4dc746d8a14060fb5fc7edd4ef5282.exe_
bb:   py2(     461) py3(     368) 79.82% - dc4dc746d8a14060fb5fc7edd4ef5282.exe_
```

We should take a closer look at this, as it could be a bug introduced in vivisect 0.2.0 or 1.0.0.

Note that there are many other binaries for which vivisect 1.0.0 extracts more features than 0.1.0. Check https://github.com/fireeye/capa/pull/421#issuecomment-786111162 for details.

**Comment by williballenthin** [comment]
can we close this?

**Comment by mr-tz** [comment]
yes 😄
