### ISSUE TITLE
use python3 for standalone builds

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#451]
migrate to distributing the standalone binaries with python 3, upgrading pyinstaller to 4.2

**Comment by williballenthin** [comment]
need utf-8 de/encoding in the spec file:
![image](https://user-images.githubusercontent.com/156560/110158017-1c6ed200-7da6-11eb-8afc-44c8015a7c94.png)

**Comment by williballenthin** [comment]
otherwise it builds, but its massive!

![image](https://user-images.githubusercontent.com/156560/110158064-285a9400-7da6-11eb-8f89-2b478eef7fca.png)

**Comment by mr-tz** [comment]
awesome, I think the bigger the program the better it is 😉
