### ISSUE TITLE
remove Py2/3 branches

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#456]
remove Py2/3 branches, e.g. `if sys.version_info >= (3, 0):`

**Comment by williballenthin** [comment]
@Ana06 yes

**Comment by williballenthin** [comment]
when we decide to make the break for py3, which is currently right after 1.6.1, we should:

  - [ ] create a tag marking the commit, so we have a place to reference if we need to backport anything
  - [ ] add an assert to main that ensures py3, to avoid any silly issues reported to gh
  - [ ] update the setup.py to specify just py3
  - start removing py2 code
    - [ ] look for `sys.version_info`
    - [ ] look for `six`
    - [ ] look for `unicode`

**Comment by Ana06** [comment]
@williballenthin 

> create a tag marking the commit, so we have a place to reference if we need to backport anything

Are you assuming that we are not merging this just after releasing 1.6.1? Because if we do, then we could just use 1.6.1 as reference. 🤔

**Comment by williballenthin** [comment]
yeah, we can use 1.6.1.

if we start providing backports, then we should have a separate branch far that, like `py2-main`
