### ISSUE TITLE
discussion: capa doesn't extract features from packed files

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#46]
capa relies on disassembly and code analysis that can easily be defeated by packing. right now, capa doesn't attempt to do any auto-unpacking, so even trivially packed samples can bypass capa. fortunately, capa can often recognize when packing is in use (if you notice a bypass, submit a rule!), and will emit a warning about this.

doing auto-unpacking is a non-trivial job, and not really in scope for the what capa does. however, if there are easy ways to make this work, we can revisit the idea.

**Comment by Maijin** [comment]
Adding a warning in the tool but also a warning in the README would be awesome!

**Comment by mr-tz** [comment]
Notes on current limitations can be found at https://github.com/fireeye/capa/blob/master/doc/limitations.md

**Comment by mr-tz** [comment]
From the SANS DFIR chat:
> Dr. Pepper
Is it possible to write a decryptor/unpacker for capa? For example if a binary uses aplib, could we write something for capa to automatically decompress and run the rest of the rules on that data?

We have ideas for some method of auto-unpack to deal with common packers (UPX, ASPack, etc) and an integration is definitely worth exploring further.

**Comment by Maijin** [comment]
Kewl, nice for the limitations.md!

**Comment by williballenthin** [comment]
we've documented the limitations and emit warnings when encountering packed files. we are no longer considering building an unpacker into capa - its a large amount of effort that will still fail pretty often. 

unpacking is left to the user; however, capa should still recommend unpacking techniques when it can.
