### ISSUE TITLE
Test if capa runs as library before release

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#460]
Add "does it run" check to `.github/workflows/build.yml`

Occurred in #459.

**Comment by Ana06** [comment]
would it make sense to test it in every PR? 🤔

**Comment by williballenthin** [comment]
> Like, why is this not triggered from the tests?

I think if `dbghelp` (windows DLL) is not available, then this will not be loaded by vivisect. since we do CI on linux this code wouldn't have been executed (theory).

**Comment by williballenthin** [comment]
we should do a CI run on `windows-latest` like @r0ny123 suggests in #459 
![image](https://user-images.githubusercontent.com/156560/110501202-2bf85e80-80b7-11eb-98b7-21c1856cd7da.png)
