### ISSUE TITLE
Compiled binary size

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#461]
The v1.6.0 binaries are between 14.8 MB and 23.2 MB. Can we optimize the file size? Or is this not even an issue?

**Comment by williballenthin** [comment]
they did grow when we switched to py3/pyinstaller4.2:

![image](https://user-images.githubusercontent.com/156560/110501905-e5573400-80b7-11eb-830c-bb9d448376ee.png)


[here](https://github.com/fireeye/capa/pull/452/files#diff-023c7253ede3c70a7bd820c1dc33df0b078dfa7fa73c330b4e8bf7c4061e09deR63-R80) i spent a bit of time cutting down the binary sizes - they were initially around 250MB!

there's probably a bit more optimization that we could do, though i suspect we might only cut off 10-20% of the size. the work involves reviewing the packages and dependencies that pyinstaller identifies and explicitly ignoring libraries that we know we'll never need at runtime.

**Comment by mr-tz** [comment]
Good points and I'm ok with leaving it as is.
