### ISSUE TITLE
explorer: make settings button more easy to identify

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#463]
> I run the plugin, found the Settings button (founding the settings took me like 5 minutes... it doesn't look like a button!)  and I selected change default rules directory... and I got that error

from @Ana06

**Comment by williballenthin** [comment]
@Ana06  can you explain what you'd like to see?

**Comment by mike-hunhoff** [comment]
how about something like this @Ana06?

![Screen Shot 2021-03-09 at 2 21 29 PM](https://user-images.githubusercontent.com/42192796/110539849-fc5f4b80-80e2-11eb-80ce-c89997de796d.png)

**Comment by mr-tz** [comment]
wow, that looks great!

**Comment by Ana06** [comment]
Awesome!!!! 💘
