### ISSUE TITLE
rule generator: It doesn't work for strings with new lines

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa#466]
Adding an string which includes `\n` produces an invalid rule, although it is possible to create a valid rule with such a string.

For example:
`Hostname:\t\t\t%s\nIP adress:\t\t\t%s\nOS version:\t\t\t%s\nUsername:\t\t\t%s\nRoot directory:\t\t%s\nTime (UTC):\t\t\t%d:%02d\n`

![Screenshot 2021-03-10 at 18 16 59](https://user-images.githubusercontent.com/16052290/110669643-d01ff980-81cc-11eb-92b1-123de65c393b.png)

Sample where I fond the bug (may be useful to reproduce the bug): [ana_sample.exe_.zip](https://github.com/fireeye/capa/files/6117676/ana_sample.exe_.zip)

**Comment by mike-hunhoff** [comment]
thank you for identifying this issue @Ana06! addressed in #468.

![Screen Shot 2021-03-25 at 1 01 29 PM](https://user-images.githubusercontent.com/42192796/112528923-53fbe900-8d6a-11eb-814d-b7a0d47b4c67.png)
