### ISSUE TITLE
UnicodeDecodeError - Capa v1.6.0

### ISSUE THREAD

**Issue by johnk3r** [fireeye/capa#469]
Hi!

In the last release (v1.16.0) I am getting the error message below when I run capa.exe on files with extension **".dll_"**. This behavior does not occur in version v1.15.0.

- In version v1.15.0 everything happens normally:

```
D:\Johnk3r\Tools\capa>capa.exe c:\Temp\offreg\ee8daedce51559f8e7f27a667f114d32.dll_  
loading : 100%|##########| 458/458 [00:00<00:00, 1103.61     rules/s]
matching:   6%|5         | 409/7044 [00:25<06:56, 15.92 functions/s]
````

- In version v1.16.0 I have the following error: 

```
D:\Johnk3r\Tools\capa>capa_new.exe c:\Temp\offreg\ee8daedce51559f8e7f27a667f114d32.dll_
loading : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 469/469 [00:00<00:00, 1240.61     rules/s]
Traceback (most recent call last):
  File "main.py", line 812, in <module>
  File "main.py", line 707, in main
  File "main.py", line 346, in get_extractor
  File "main.py", line 329, in get_extractor_py3
  File "main.py", line 278, in get_workspace
  File "viv_utils\__init__.py", line 80, in getWorkspace
  File "vivisect\__init__.py", line 262, in loadWorkspace
  File "vivisect\storage\basicfile.py", line 57, in loadWorkspace
  File "vivisect\storage\basicfile.py", line 47, in vivEventsFromFile
UnicodeDecodeError: 'ascii' codec can't decode byte 0x90 in position 2: ordinal not in range(128)
[4072] Failed to execute script main
````

Tk.

**Comment by williballenthin** [comment]
can you confirm that there are not any related `*.viv` files in that directory? if so, can you delete them and try again?

the underlying vivisect workspace format is not compatible across py2/py3, and we've missed this issue in the update to py3.

**Comment by Ana06** [comment]
What about introducing a nicer exception when getting an `UnicodeDecodeError` while reading `.viv` files. Something like: `Reading '<name>.viv' file failed, you may be using a .viv file generated with Python 2 (not compatible with Python 3`.

I think it is ok that `.viv` files are not compatible (they can always be regenerated when updating to Python3), but I think we should have documented this better (CHAGELOG/release notes and better error). Should we change the CHANGELOG/release notes now to document this?

**Comment by mr-tz** [comment]
Yes, that exception and others when generating the workspace, should be handled better. In capa is fine by me.

Documenting this better is another great idea. Let's add a warning in the changelog and/or release notes as you suggest.

**Comment by johnk3r** [comment]
> 
> 
> can you confirm that there are not any related `*.viv` files in that directory? if so, can you delete them and try again?
> 
> the underlying vivisect workspace format is not compatible across py2/py3, and we've missed this issue in the update to py3.

You are sure!
In my tests the problem occurs when I run v.1.16 in a file that was analyzed by v.1.15 and that generated ".viv".

After removing the file the problem does not happen.

**Comment by Ana06** [comment]
I have created a PR in viv-utils to provide a better exception, as in viv utils we can ensure we only raise this exception when loading a `.viv` file easily: https://github.com/williballenthin/viv-utils/pull/16

There is also a PR to update the CHANGELOG/release notes: https://github.com/fireeye/capa/pull/475

**Comment by williballenthin** [comment]
viv-utils v0.5.0 released

**Comment by mr-tz** [comment]
Thanks for reporting. We've updated viv-utils and the documentation, so closing this now.

**Comment by Ana06** [comment]
But we still need to use the new version of viv-utils: https://github.com/fireeye/capa/blob/df36bb9f35b33dcc2c2a8681d080339b5f717461/setup.py#L31 I'll send a PR! 😉
