### ISSUE TITLE
discussion: capa doesn't do anything for non-Windows or non-PE files

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#47]
capa contains a small amount of code and a large amount of default rules that assume the input file is a Windows PE file. this is because the original authors primarily analyze Windows malware. there is nothing stopping analysis of Linux ELF or MacOS Mach-O binaries; however, we haven't yet had the experience, sample binaries, nor time to make this happen.

support for additional platforms may be added in the future, especially with (1) contributions from experts in those fields, and  (2) sufficient sample binaries to demonstrate capa works as expected. if you're interested in helping out in these areas, please get in touch!

**Comment by Maijin** [comment]
Would be nice to add basic support for script based file - (not speaking about emulation but just checking for strings could easily be enough to cover a lot).

**Comment by williballenthin** [comment]
that's a good point, though I wonder if rules are strictly strings-based, then yara might be a better fit? but, we market "capa for capabilities, yara for detection" (oversimplified) so we should find a way to explain this with more nuance.

**Comment by re-fox** [comment]
Non-pe work would be a welcome addition.  

If it helps, I could begin to lay some initial rule groundwork by contributing some linux rules.  Maybe toss them into a testing repo on my own account (knowing they don't do anything initially) and as changes come in for capa, I can help test.

**Comment by williballenthin** [comment]
@re-fox I think that would be quite useful.

We'll have to extend the rule syntax a bit, probably `rule.meta.os/arch/platform`, to help specify when to run a rule.

It would be a huge help to have a base set of rules and samples that we'd expect to match, and from which we can build Linux support. With this foundation, its much easier to implement the framework and supporting analysis.

**Comment by re-fox** [comment]
I tossed up a repo here (https://github.com/re-fox/capa-rules-linux) with some basic rules to start.  I'll be slowly adding to these in the next couple weeks.  

The format is largely mirroring the current capa-rules repository.

**Comment by williballenthin** [comment]
#699 for ELF support

**Comment by williballenthin** [comment]
@re-fox we'd love to incorporate your linux rules now that we have ELF/Linux support!

**Comment by williballenthin** [comment]
we've added support for ELF files and various Unix-like operating systems. macOS binaries are primarily limited by not having any real ruleset to start with. but there's not any inherent limitation. .NET module support is being considered. scripting language support is not currently being considered at this time.

please open new issues to request support for specific file formats or OSes.
