### ISSUE TITLE
rule generator: tab removes selected text

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa#471]
Pressing `tab` while selecting some text in the capa explorer Rule generator preview removes the text. This in specially unexpected when selecting several lines to change the indentation of all of them as once.

https://user-images.githubusercontent.com/16052290/110834881-607a3f00-829e-11eb-9767-91ffe8bf25c4.mov

**Comment by williballenthin** [comment]
to characterize this a bit: this is behavior like you'd see in a text editor rather than you'd see in a code editor.

**Comment by Ana06** [comment]
@williballenthin 
> to characterize this a bit: this is behavior like you'd see in a text editor rather than you'd see in a code editor.

I needed to try this to believe it 😮 The IDA database notepad seems to behave similarly... ok, let's call this a feature request and not a bug. 💡

**Comment by mike-hunhoff** [comment]
addressed in #488
