### ISSUE TITLE
rule generator: future request - highlight features at location

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa#473]
It would be really cool if when selecting a location in the IDA view, the rule generator opened and highlighted the extracted features at that location. I find myself expending a lot of time looking for the wanted feature in the features view. The search helps but if you look for a number, this still gives a lot of results when having a lot of features. I think that highlighting extracted features would significantly speed the process up. I don't know how easy this is to implement thought (or if it is even possible).

Another solution is to have an option to ONLY show the features at the current location. This may be easier to implement and maybe even more useful when having many features.

**Comment by williballenthin** [comment]
`ida_kernwin.UI_hooks.screen_ea_changed(self, ea, prev_ea)` can receive notification of this.

**Comment by mike-hunhoff** [comment]
I'm thinking something like this (needs a couple touches before PR):

https://user-images.githubusercontent.com/42192796/110877912-759f9f80-8297-11eb-8939-11aca396fbee.mov

**Comment by Ana06** [comment]
Wooow!!! That's so great!!! 😮

**Comment by mr-tz** [comment]
Really awesome! Alternative selection strategies I like are:
- current basic block
- currently selected EA +/- 40 instructions/heads

**Comment by mike-hunhoff** [comment]
I've added this feature with PR #692. For now I've opted for the simplest implementation to balance ROI. I'll document the other filter suggestions in #603 to be revisted in the future if needed.
