### ISSUE TITLE
rule linter line ending inconsistency

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#482]
in https://github.com/fireeye/capa-rules/pull/297, @MalwareMechanic authors a rule with a comment at the end of a line, like `foooo # comment`. in this case, the linter requires `\r\n` to end the commented line, but `\n` elsewhere.

we should use consistent line endings everywhere.

![image](https://user-images.githubusercontent.com/156560/111677692-11c02e00-87e5-11eb-99d7-2878db6b90ae.png)

**Comment by mr-tz** [comment]
working on something for this

**Comment by mr-tz** [comment]
ah, have to look into the linter/capafmt as well...

**Comment by mr-tz** [comment]
I think commented lines are kept as they are for the roundtrip conversion. If they have CRLF EOLs before running capafmt, they will stay like that.
