### ISSUE TITLE
linter: debug logging is broken

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#483]
the linter accepts `-d` to enable debug logging; however, it also sets `logging.getLogger("capa").setLevel(logging.CRITICAL)` which overrides the `capa.linter` logger. this means `-d` doesn't work.

**Comment by mr-tz** [comment]
on it!

**Comment by williballenthin** [comment]
@mr-tz  see associate PR

**Comment by mr-tz** [comment]
too slow
