### ISSUE TITLE
CI: pin OS versions?

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#490]
Ui, good catch. We should better pin a concrete version for all tests then?!
For example, Ubuntu 20 doesn't come with Python 2, although I think we will dodge that bullet by going Py3 only soon 🤞

_Originally posted by @mr-tz in https://github.com/fireeye/capa/pull/476#r594281103_

**Comment by williballenthin** [comment]
i think this is a good idea. CI for lancelot just broke because they upgraded from ubuntu 18 to 20 and i ignored all the warnings. the more explicit, the better.
