### ISSUE TITLE
IDA 7.6 not supported

### ISSUE THREAD

**Issue by stevemk14ebr** [fireeye/capa#496]
IDA 7.6 is not in the helpers list here: https://github.com/fireeye/capa/blob/cfa904a0a01e972cab67ed92370d7996458240d4/capa/ida/helpers/__init__.py#L21-L26

This causes the plugin to fail to load with 
```
[WARNING] This plugin does not support your IDA Pro version	(__init__:is_supported_ida_version)
[WARNING] Your IDA Pro version is: 7.6. Supported versions are: 7.1, 7.2, 7.3, 7.4, 7.5.	(__init__:is_supported_ida_version)
```

**Comment by mike-hunhoff** [comment]
we are waiting for hex-rays to release a fix - following that we can merge this PR to enable IDA 7.6 support.

**Comment by mr-tz** [comment]
If you have an IDA license, you can contact Hexrays directly and ask for a fix. This affects the capa plugin and likely any other plugin using PyQt QTreeWidgets.

**Comment by calisurferbro25** [comment]
after using hexrays' QtWidgets.pyd fix and manually adding 7.6 to capa package it works fine, why not merge already?

**Comment by williballenthin** [comment]
we'd like to see if Hex-Rays will release an update to IDA to distribute the patched Qt widgets. if we merge, then most people will find out the hard way that they have to make a special request to hex-rays to get the patch - and i think this might be quite confusing.

is there a way we can detect the buggy version and show users a dialog box with recommendations under 7.6?

**Comment by Lichtlos** [comment]
The updated QtWidgets.so files have been provided by Hex-Rays today:

https://www.hex-rays.com/blog/ida-7-6-empty-qtreeview-qtreewidget/

**Comment by williballenthin** [comment]
7.6sp1 released today including bugfix for this issue: https://www.hex-rays.com/products/ida/news/7_6sp1/
