### ISSUE TITLE
pin all dependencies

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#498]
we're missing a bunch of version pins in our setup.py, which exposes the project to future breakages:

![image](https://user-images.githubusercontent.com/156560/112360429-ebdcd280-8c97-11eb-9b3f-66a85d463c8e.png)

**Comment by mr-tz** [comment]
It's biting us already, I believe:

`ruamel.yaml`: "The 0.16.13 release was the last that will tested to be working on Python 2.7."

**Comment by Ana06** [comment]
This has been addressed in https://github.com/fireeye/capa/pull/504, right?

**Comment by mr-tz** [comment]
#504 only pinned ruamel, the other dependencies are still TODO

**Comment by Ana06** [comment]
ouch! 🙈  I'll send a PR to pin the rest in a moment! 👍
