### ISSUE TITLE
Option to disable .viv workspace creation

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#507]
on a related note of `capa`/`vivisect`, is there any way (e.g. command-line switch parameter) to disable the creation of the extra ".viv" workspace file?

_Originally posted by @evandrix in https://github.com/vivisect/vivisect/issues/383#issuecomment-808953663_

**Comment by williballenthin** [comment]
should we disable all viv file creation? still use the viv if it happens to be there, but not create them ourselves?

this would reduce clutter on users' systems but reduce performance in the case that capa is run multiple times on the same program.

**Comment by mr-tz** [comment]
hmm, I'm torn as I like the performance boost on multiple runs but can see how it can be unnecessary or even confusing to create the workspaces for most users

@evandrix in what way are the viv files causing issues for you?

**Comment by evandrix** [comment]
it's more a pain point / convenience if there was such an option, than a real issue that needs help fixing

my use case: "on a 48-core, 128GB Linux VM on ESXi, I have a corpus of 500k+ malware samples in a folder, that i'm running `capa` on, via `parallel` (initially was using the `capa` release binary, later switched to `pip`-installing `capa` + `git clone`ing `capa-rules`, because of all the `_MEI*` folders it was creating under /tmp - which I later found could be configured to `pwd`) all i want out of doing this is input:malware sample binary => output:list of values that are in the "mbc" fields of the output JSON

the execution died when i ran out of space on /tmp, due to the `_MEI*` folders (typical for a PyInstaller exe), and then later ran out of space on `pwd`, because the `.viv` can be substantially large, as i later found out

**Comment by evandrix** [comment]
additionally, more details of how i'm running it, for your reference here https://github.com/fireeye/capa/issues/509

it doesn't complete on those samples mentioned in that issue, for some reason

**Comment by williballenthin** [comment]
i feel your pain :-)

when we run floss and capa within our pipelines, we restrict the resources and bail if its looking like the analysis won't work. for example, i think we set runtime cap at 5mins and memory usage at maybe 1GB. in our experience, if this isn't enough, its unlikely that waiting longer or working harder is likely going to make much difference.

**Comment by williballenthin** [comment]
see discussion here: https://github.com/fireeye/capa/discussions/581

re-raising the idea of disabling .viv creation by default

**Comment by mr-tz** [comment]
If we disable it by default, which may make sense for the general user only running capa once on a sample, we should add an option and/or a config file we can use to enable it for (rule) developers.

**Comment by williballenthin** [comment]
what if we just support running capa against existing .viv files and leave it up to rule authors to generate .viv files, such as with `vivbin -B malware.exe`, if they want this performance boost?

**Comment by mr-tz** [comment]
I'm against the additional step to create the viv file. I'm more and more leaning towards a profile/config file. That could store things like shown below and be reused by the IDA plugin.
```
SAVE_WORKSPACE = True
RULE_USER_NAME = @mr-tz
RULES_DIR = /home/user/rules
...
```

**Comment by mr-tz** [comment]
https://github.com/welbornprod/easysettings

**Comment by williballenthin** [comment]
during weekly phone sync, we generally agreed to disable workspace creation by default, while keeping an option to enable for advanced users, such as rule developers.

TODO: explain rational here

**Comment by williballenthin** [comment]
TODO: describe how this will be configured

**Comment by mr-tz** [comment]
Adding to this, I think we can easily use both 3) and 1) (at a later point) in tandem.

We currently have the `analyzing program` spinner. Maybe we can extend this to indicate how users can potentially speed things up if they analyze files multiple times, e.g.

```
a)
$ capa sample.exe
loading : 100%|██████| 582/582 [00:00<00:00, 1292.01 rules/s]
\ analyzing program (program analysis .viv file is not saved, enable saving via CAPA_SAVE_WORKSPACE to speed up future analysis of this file)
```

or in a separate line
```
b)
$ capa sample.exe
loading : 100%|██████| 582/582 [00:00<00:00, 1292.01 rules/s]
program analysis .viv file is not saved, enable saving via CAPA_SAVE_WORKSPACE to speed up future analysis of this file
\ analyzing program
```
