### ISSUE TITLE
Analysis doesn't terminate

### ISSUE THREAD

**Issue by evandrix** [fireeye/capa#509]
Is your bug report related to capa rules (for example a false positive)? No
Have you checked that your issue isn't already filed? Yes
Have you read capa's Code of Conduct? Yes
Have you read capa's CONTRIBUTING guide? Yes

### Description

Analysis seems to go on forever (at least, I've left it running for many hours, and it doesn't complete) for the following samples:

- SHA256:`a34f59f7f84b2fdb7526cfd4dfc763e1f17bb8a62461915232d7b84ae34987eb` [7ae9d136ff12f5da6b14c291ab07d88afbbde5ab.zip](https://github.com/fireeye/capa/files/6245942/7ae9d136ff12f5da6b14c291ab07d88afbbde5ab.zip)
- SHA256:`aeeed92dfe809de7e0bc73d4cfbbd5e98d58ac2e47a45eb3b9dbf17ce137812b` [776e44dcfbfe05c52ef35712fd7dd4797072b087.zip](https://github.com/fireeye/capa/files/6245944/776e44dcfbfe05c52ef35712fd7dd4797072b087.zip)
- SHA256:`c958b0a303c88a3bc7af51325a140c93c673774bcbf830e091566502a8f5ca56` [20520e5dc8847d74f35e6c466382fb0962e30a89.zip](https://github.com/fireeye/capa/files/6245945/20520e5dc8847d74f35e6c466382fb0962e30a89.zip)
- SHA256:`13f1759025bf679c201eeadd4576cb0938745064a08f82769016a8d626d8d62c` [d70464726bc0c39076a2c1e699eba1cdb1926406.zip](https://github.com/fireeye/capa/files/6245946/d70464726bc0c39076a2c1e699eba1cdb1926406.zip)

_Not sure whether the issue lies with `capa`, or the `vivisect` dependency_

### Steps to Reproduce

1. download v1.6.0 release of the `capa` binary from this code repository
2. execute the binary, by invoking it as such `capa-v1.6.0 -q -j --color never -f pe -b vivisect /path/to/file`
3. wait for eternity...

* i've tried to give the VM 128GB RAM, as `capa` seems to be memory-intensive in its processing, to no avail (why wasn't this written in Golang)

**Expected behavior:**

- Analysis should finish in a reasonable amount of time e.g. <1min, producing a .json output file, and printing any warning/error output to console (if any)

**Actual behavior:**

- `capa` process is still running, even after a very long time

### Versions

- `capa` version 1.6.0
  - standalone tool
- Python v3.8.x
- Ubuntu Linux v20.04.2 LTS / CentOS Linux v7.9.2009 (Core)

### Additional Information

Nil

---
Aside: typographical error in template
~~sybmodules~~ submodules
```# Is your bug report related to capa rules (for example a false positive)?
We use sybmodules to separate code, rules and test data. If your issue is related to capa rules, please report it at https://github.com/fireeye/capa-rules/issues.```

**Comment by williballenthin** [comment]
7ae9d136ff12f5da6b14c291ab07d88afbbde5ab

VB sample with a *massive* function at 0x4033E0:

![image](https://user-images.githubusercontent.com/156560/113344021-cbdb8d80-92ed-11eb-9e47-886fa32128dc.png)

IDA won't display the function.

**Comment by williballenthin** [comment]
triage 776e44dcfbfe05c52ef35712fd7dd4797072b087

packed and function at 0x140C3F184 is somewhat complicated:
![image](https://user-images.githubusercontent.com/156560/113344298-1f4ddb80-92ee-11eb-89e5-31641413f904.png)

**Comment by williballenthin** [comment]
triage 20520e5dc8847d74f35e6c466382fb0962e30a89

vmprotect'd 10MB binary

**Comment by williballenthin** [comment]
triage d70464726bc0c39076a2c1e699eba1cdb1926406

packed 13MB binary

**Comment by evandrix** [comment]
> triage d70464726bc0c39076a2c1e699eba1cdb1926406
> 
> packed 13MB binary

i thought it would say something like the following, if it were packed:
```WARNING:capa:--------------------------------------------------------------------------------
WARNING:capa: This sample appears to be packed.
WARNING:capa:
WARNING:capa: Packed samples have often been obfuscated to hide their logic.
WARNING:capa: capa cannot handle obfuscation well. This means the results may be misleading or incomplete.
WARNING:capa: If possible, you should try to unpack this input file before analyzing it with capa.
WARNING:capa:
WARNING:capa: Use -v or -vv if you really want to see the capabilities identified by capa.
WARNING:capa:--------------------------------------------------------------------------------```

**Comment by evandrix** [comment]
> triage 7ae9d136ff12f5da6b14c291ab07d88afbbde5ab
> 
> VB sample with a _massive_ function at 0x4033E0:
> 
> ![image](https://user-images.githubusercontent.com/156560/113344021-cbdb8d80-92ed-11eb-9e47-886fa32128dc.png)
> 
> IDA won't display the function.

is it possible to  have some sort of default internal setting within `capa`, to not bother analysing functions that are "excessively large"?

**Comment by williballenthin** [comment]
> i thought it would say something like the following, if it were packed:

definitely, and we'll update our rules to better catch some of these samples.

note, however, that there's a chicken and egg problem here: in order to find packed samples, we need to analyze them, and if they're packed, they don't analyze well (or take lots of time/resources). i bet we can create some initial filter logic to avoid some difficult binaries.

**Comment by williballenthin** [comment]
> is it possible to have some sort of default internal setting within capa, to not bother analysing functions that are "excessively large"?

maybe, with a bit of rearchitecting. as is, we currently hand analysis over to vivisect to build up a workspace, and then process that workspace when its ready. in order to bail early, we'd have to hook into vivisect to be notified of these cases. it might be possible, if we can identify a consistent set of characteristics.

**Comment by evandrix** [comment]
> > i thought it would say something like the following, if it were packed:
> 
> definitely, and we'll update our rules to better catch some of these samples.
> 
> note, however, that there's a chicken and egg problem here: in order to find packed samples, we need to analyze them, and if they're packed, they don't analyze well (or take lots of time/resources). i bet we can create some initial filter logic to avoid some difficult binaries.

yeah, i understand, and i'm willing to live not perfectly getting everything, too bad https://unpac.me is not released publicly

**Comment by evandrix** [comment]
> > is it possible to have some sort of default internal setting within capa, to not bother analysing functions that are "excessively large"?
> 
> maybe, with a bit of rearchitecting. as is, we currently hand analysis over to vivisect to build up a workspace, and then process that workspace when its ready. in order to bail early, we'd have to hook into vivisect to be notified of these cases. it might be possible, if we can identify a consistent set of characteristics.

"hand analysis over to vivisect " - yep, i kinda got that

**Comment by williballenthin** [comment]
> use something like detect it easy to identify a packer

do you happen to know the packers in use here?

  - 7ae9d136ff12f5da6b14c291ab07d88afbbde5ab: VB, and we could bail upon seeing those imports
  - 776e44dcfbfe05c52ef35712fd7dd4797072b087: ???
  - 20520e5dc8847d74f35e6c466382fb0962e30a89: vmprotect, and we could bail upon seeing those section names
  - d70464726bc0c39076a2c1e699eba1cdb1926406: ????, though its big. should we bail on any file with large code section?

**Comment by evandrix** [comment]
For your convenience, the output from Detect-It-Easy v3.01

`776e44dcfbfe05c52ef35712fd7dd4797072b087`
```
{
	"arch":"AMD64",
	"detects":[
		{"name":"VMProtect","options":"-","string":"protector: VMProtect(-)[-]","type":"protector","version":"-"},
		{"name":"Microsoft Linker","options":"Console64,console,admin","string":"linker: Microsoft Linker(14.14)[Console64,console,admin]","type":"linker","version":"14.14"}
	],
	"endianess":"LE",
	"filetype":"PE64",
	"mode":"64",
	"type":"Console"
}
```

`d70464726bc0c39076a2c1e699eba1cdb1926406`
```
{
	"arch":"I386",
	"detects":[
		{"name":"VMProtect","options":"-","string":"protector: VMProtect(1.X)[-]","type":"protector","version":"1.X"},
		{"name":"Microsoft Linker","options":"GUI32,signed","string":"linker: Microsoft Linker(14.16, Visual Studio 2017 15.9*)[GUI32,signed]","type":"linker","version":"14.16, Visual Studio 2017 15.9*"}
	],
	"endianess":"LE",
	"filetype":"PE32",
	"mode":"32",
	"type":"GUI"
}
```

**Comment by williballenthin** [comment]
idea: we could run the file feature matcher first and inspect it for packer rule hits before doing the viv analysis. then our vmprotect, etc. rules can match on obvious file features (like section names) and prevent any crazy runtimes by the analyzer.

**Comment by williballenthin** [comment]
the proposed solution (lightweight first pass to detect packers) was merged and i think these samples are handled much better now (you get a warning that capa won't work well).

please reopen if there are further enhancements we can make to support your workflow.
