### ISSUE TITLE
IDA extractor canonic mnem vs. mnem

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#514]
In the IDA extractor we use the canonic mnemonic vs. the specific one. This differs to vivisect's analysis (I haven't checked SMDA).

Given this code:
```asm
.text:00419FAB AC                lodsb
```

# IDAPython
```python
print_insn_mnem(here())
'lodsb'
```

We use this in the feature extractor:
```
insn = idautils.DecodeInstruction(here()); print(insn.get_canon_mnem())
lods
```

# vivisect
vivisect gives `lodsb`

# Question
To make this more consistent should we always use the non-canonic, e.g. `lodsb`, instruction? IDA's `insn_t` doesn't seem to have a function to get this easily.

**Comment by mike-hunhoff** [comment]
We should be consistent here. Let's update the IDA extractor to extract `lodsb`
