### ISSUE TITLE
IDA Plugin Doesn't Support IDA 7.6

### ISSUE THREAD

**Issue by MalwareMechanic** [fireeye/capa#532]
### Description

The most recent release, v1.6.2, is missing support for IDA 7.6 in the file `C:\<python_version>\Lib\site-packages\capa\capa\ida\helpers\__init__.py`.

### Steps to Reproduce

0. Install patch for IDA 7.6 to fix QT issue
1. Install via pip: `pip install flare-capa`
2. Copy over `capa_explorer.py` to IDA plugins directory
3. Open a file in IDA 7.6

**Expected behavior:**

Be able to launch capa explorer plugin via `Edit`->`Plugins` -> `FLARE capa explorer`.

**Actual behavior:**

Message in IDA output specifying IDA 7.6 is not a supported version:
```
[WARNING] This plugin does not support your IDA Pro version	(__init__:is_supported_ida_version)
[WARNING] Your IDA Pro version is: 7.6. Supported versions are: 7.1, 7.2, 7.3, 7.4, 7.5.	(__init__:is_supported_ida_version)
```

### Versions

Running Windows 7 x64 with Python 3.7.9. Installed capa via pip (`pip install flare-capa`). Using IDA Pro integration (capa explorer).

`capa --version`
> capa 1.6.2

### Additional Information

Also seems master's version didn't get bumped to 1.6.2. See: https://github.com/fireeye/capa/blob/master/capa/version.py

**Comment by mr-tz** [comment]
I think IDA's official fix came out after we released `v1.6.2`, so currently you have to pull from master or edit the file manually as a workaround.

**Comment by williballenthin** [comment]
shall we do a v1.6.3 to update the explorer?

**Comment by mike-hunhoff** [comment]
@mr-tz is right - `v1.6.2` does not include IDA 7.6 support.

+1 for `v1.6.3`.

**Comment by seifreed** [comment]
Do we have any ETA for the capa explorer fix?

**Comment by williballenthin** [comment]
> Do we have any ETA for the capa explorer fix?

we'll get it out this week, by Friday, hopefully sooner

**Comment by Ana06** [comment]
capa v1.6.3 (including IDA 7.6 support) released: https://github.com/fireeye/capa/releases/tag/v1.6.3

**Comment by seifreed** [comment]
I just tested the latest version:

`git pull` in the repository

`python3 setup.py build && python3 setup.py install
`
I copied the capa_explorer.py to the IDA 7.6 plugins folder, but I'm still getting:

`WARNING:capa:Your IDA Pro version is: 7.6. Supported versions are: 7.1, 7.2, 7.3, 7.4, 7.5.
`
I'm missing something here?

**Comment by r0ny123** [comment]
https://github.com/fireeye/capa/blob/master/capa/ida/plugin/README.md#ida-76-caveat-ida-76sp1-or-patch-required

**Comment by seifreed** [comment]
Yes I have that SP1 applied. Fixed on my own, It was another local problem!

Thanks for the fast patch!
