### ISSUE TITLE
Discussion: what should we include in the changelog?

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa#550]
From https://github.com/fireeye/capa/pull/549:

## Should we include capa rules updates apart from new rules?
![Screenshot 2021-05-07 at 16 31 37](https://user-images.githubusercontent.com/16052290/117465170-b3e0d480-af51-11eb-8839-ec6160296472.png)

## Do we want to include dependency updates?
![Screenshot 2021-05-07 at 16 31 05](https://user-images.githubusercontent.com/16052290/117465100-a0356e00-af51-11eb-9b9e-c1bdaff15356.png)

Opinions? 😄

**Comment by Ana06** [comment]
@williballenthin @mike-hunhoff opinions? 😄

**Comment by williballenthin** [comment]
personal votes:

> Do we want to include dependency updates?
no

> Should we include capa rules updates apart from new rules?
no, unless major efforts like ATT&CK mappings

also:

  1. we should have a "breaking changes" section for major version releases that is shown near the top to highlight things that could cause API users problems, and
  2. we should always have a (non-breaking) "changes" section for things we worked on, unless they're trivial (see above dep updates).
