### ISSUE TITLE
fail to analyze DriverEntry and other recognized library functions

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#564]
While we want to skip over most library functions for analysis, certain functions should be analyzed!

See `493167e85e45363d09495d0841c30648.sys_:0x401000` == `DriverEntry`.

This should include the below strings and their variations
```
DriverEntry
main
wmain
WinMain
DllMain
```

Maybe we can just look for the `main` substring although that will also capture functions like `_domain_err` or `___tmainCRTStartup`.

**Comment by williballenthin** [comment]
in the 4931... `DriverEntry` is the OEP of the .sys file:

![image](https://user-images.githubusercontent.com/156560/118845476-0cd13680-b889-11eb-8fb1-764a23e10b3c.png)

**Comment by williballenthin** [comment]
"works on my machine"

![image](https://user-images.githubusercontent.com/156560/118846141-a7ca1080-b889-11eb-9fe0-dbd84bbbe193.png)

**Comment by mr-tz** [comment]
huh, sorry I messed up 🙈 
will investigate what's really going on with the failed test

**Comment by williballenthin** [comment]
![image](https://user-images.githubusercontent.com/156560/118846830-55d5ba80-b88a-11eb-8a6e-fc33058e1e8a.png)
lint does fail on my machine. will dig into this further.

**Comment by mr-tz** [comment]
it fails on the second example which appears to really be a library function

**Comment by williballenthin** [comment]
![image](https://user-images.githubusercontent.com/156560/118847075-9a615600-b88a-11eb-8dce-8521d15a5bba.png)
confirmed

**Comment by williballenthin** [comment]
![image](https://user-images.githubusercontent.com/156560/118847402-ef9d6780-b88a-11eb-9571-f4ab7e33fa06.png)

IDA/FLIRT identifies as library code (like Moritz said)

**Comment by mr-tz** [comment]
Never mind me 🤦

**Comment by williballenthin** [comment]
![image](https://user-images.githubusercontent.com/156560/118847930-810cd980-b88b-11eb-9975-5331b99698f6.png)
capa ignores the example function
