### ISSUE TITLE
enable matching on namespaces

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#590]
in order to detect that a category of rules match, without hardcoding all the options, we'd like to be able to write statements that specify that a namespace must much. for example, a statement like `match: anti-analysis/packer` would match if any rule with this namespace (prefix) also matches.

we can currently write rules that contain statements like `match: writes to TCP socket` to indicate the rule with name `writes to TCP socket` must match for the parent rule to match. today, if we wanted to specify "packed AND writes to TCP socket" we'd have to hardcode all the packer rules in a large `AND` block, which is a point of maintenance when new packer rules are added.

i propose extending the `match` statement to also match namespaces. because namespaces and rule names are typically formatted differently (kebab-case with slashes vs human readable sentence fragments) they should rarely/never overlap.

this supports #390

**Comment by williballenthin** [comment]
implementation should be pretty easy - when we emit a `Match` for a rule name, also emit a `Match` for all of its namespace prefixes (that is, if namespace is `a/b/c`, emit `Match(a/b/c)`, `Match(a/b)` and `Match(a)`).

**Comment by williballenthin** [comment]
huh, we may already support some of this functionality?

![image](https://user-images.githubusercontent.com/156560/120002044-a7203100-bf91-11eb-9aeb-1aa2df43f424.png)
https://github.com/fireeye/capa/blob/master/capa/rules.py#L449-L489

if you specify `match: anti-analysis/packer` than the rule engine expands the dependencies needed

**Comment by williballenthin** [comment]
wow we already have tests, too

https://github.com/fireeye/capa/blob/master/tests/test_engine.py#L401-L470

i guess this already exists :-O

**Comment by williballenthin** [comment]
ah, here is the namespace match generation:

![image](https://user-images.githubusercontent.com/156560/120003135-b05dcd80-bf92-11eb-942d-5b9058390931.png)

https://github.com/fireeye/capa/blob/master/capa/engine.py#L259-L263

**Comment by mr-tz** [comment]
good work 😜

**Comment by williballenthin** [comment]
already documented, too. closing issue as already complete.

**Comment by williballenthin** [comment]
im just padding my stats here.
