### ISSUE TITLE
CAPA MacOS release detected as malicious on VirusTotal

### ISSUE THREAD

**Issue by fritzfs** [fireeye/capa#614]
### Description

CAPA is detected as malicious by two AV vendors. 

Please see this VirusTotal report for CAPA MacOS release.

https://www.virustotal.com/gui/file/cd47b9d0106a23d82e8a5626451b9354871cfc5965d534cceb28f9f8e2dae06f/detection

### Steps to Reproduce

Upload CAPA official binary to VirusTotal

### Versions

capa v1.6.3-0-gc547519

**Comment by williballenthin** [comment]
that's unfortunate. perhaps we can find a way to contact K and recommend that they enhance their signatures.

my guess is that they unpack the pyinstaller executable and recognize coinmining related strings found within the embedded rules. we're not going to change the way that capa is structured any time soon, so we'll have to work with the AV vendors to get this fixed.

**Comment by williballenthin** [comment]
FP reporting process for K: https://support.kaspersky.com/viruses/answers/1870

**Comment by williballenthin** [comment]
https://opentip.kaspersky.com/CD47B9D0106A23D82E8A5626451B9354871CFC5965D534CCEB28F9F8E2DAE06F/

![image](https://user-images.githubusercontent.com/156560/121057989-1c071e00-c77d-11eb-814e-20d75fc6ba66.png)

**Comment by williballenthin** [comment]
![image](https://user-images.githubusercontent.com/156560/121058201-51ac0700-c77d-11eb-9def-b44e2d02cc3b.png)

**Comment by williballenthin** [comment]
![image](https://user-images.githubusercontent.com/156560/121058617-c4b57d80-c77d-11eb-82e7-d5448d9ed116.png)

**Comment by williballenthin** [comment]
![image](https://user-images.githubusercontent.com/156560/121096977-77063880-c7b0-11eb-9af3-7276bbcf0e03.png)

**Comment by williballenthin** [comment]
this is now fixed:

![image](https://user-images.githubusercontent.com/156560/123696937-8dd10580-d819-11eb-9f71-04649969ee2d.png)
