### ISSUE TITLE
ida explorer: functionname feature not supported

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#616]
### Description

For rules with `function-name` features the IDA explorer may complain and fail to render any results:

```
ERROR:capa.ida.plugin.form:Failed to render results (error: unexpected feature type: functionname)
INFO:capa.ida.plugin.form:Analysis failed.
```

I think the new feature needs to be added to explorer and rule generator?

**Comment by williballenthin** [comment]
🤦🏼 im sorry
