### ISSUE TITLE
`--signature` option clarifications

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#630]
Currently the `--signature` option adds to the existing default sig path. I find this option a little confusing and inconsistent with the `--rules` option for example.

Most commonly I probably would want to specify my own sig directory although a single sig file should work as well.

I suggest to:
- make this consistent with the `rules` option and/or
- better document this in the help (epilog) via an example usage

**Comment by williballenthin** [comment]
lets get this in before v2.0
