### ISSUE TITLE
remove freeze?

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#638]
we have a lot of code to support the "freeze" file format of serialized capa features. this was originally implemented so that we could pre-compute the features of a sample and subsequently match rules multiple times. however, i'm not aware that we (or anyone) uses this feature. therefore, we should consider removing it to avoid bitrot.

**Comment by williballenthin** [comment]
@mr-tz this format appears to serve the same purpose as the saved .viv files during rule testing? is one a better fit than another?

**Comment by mr-tz** [comment]
if we don't want to use it for things like #424 I agree
I think theoretically, frz could speed up things heavily for multiple runs, but we don't really decided to leverage it

**Comment by williballenthin** [comment]
freeze might also be used to separate the "front end" (feature extraction) from the "back end" (matcher and formatter)

**Comment by williballenthin** [comment]
will not remove at this time
