### ISSUE TITLE
absolutely do not process non-pe files even when --format pe

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#642]
as reported in #641, the user can override the file format detection and provide `--format pe` even when the underlying file is clearly not a PE. we should detect this scenario and either:

  1. warn very loudly that this is not a PE, or
  2. refuse to pass analysis to vivisect

**Comment by mr-tz** [comment]
I prefer 2. because I think it's best to minimize potential confusion and be explicit about what capa can and can't do.
