### ISSUE TITLE
use `function-name` feature in function scope

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#657]
![2021-06-23_15-05-02](https://user-images.githubusercontent.com/17606537/123101646-9057e780-d434-11eb-954f-dbe852e597f8.png)

for example: should users be able to add `- function-name: _exit` for function scope rules

with this we could extend the `check mutex and exit` rule

currently this gives:
```
invalid rule: feature function-name(_exit) not support for scope function
```

**Comment by mr-tz** [comment]
another use case: PMA Lab 11-03.exe

```asm
.text:00401313 68 74 91 40 00    push    offset Command  ; "net start cisvc"
.text:00401318 E8 9F 00 00 00    call    _system
```

**Comment by williballenthin** [comment]
these names should be accessible via `api: _exit`

**Comment by mr-tz** [comment]
:( that doesn't work

**Comment by mr-tz** [comment]
There's no code in IDA's insn extractor. For viv I may still be having issues with my setup 😕

**Comment by williballenthin** [comment]
ahh, ok. yeah here's the code for viv: https://github.com/fireeye/capa/blob/master/capa/features/extractors/viv/insn.py#L119-L122

sounds like we need to update the IDA extractor to support this feature, too

**Comment by mr-tz** [comment]
yes, vivisect works, my setup was causing the issue
