### ISSUE TITLE
KeyError: anti-analysis/packer

### ISSUE THREAD

**Issue by BlastyCZ** [fireeye/capa#673]
### Description
I'm trying to use capa as python module. It was working a few months ago. I'm finally able to play with it, but suddenly it stopped working.

### Steps to Reproduce

```
rules = get_rules(RULES_PATH, disable_progress=True)
rulesSet = RuleSet(rules)
extractor = get_extractor(file_path, FORMAT, BACKEND_VIV, disable_progress=True)
meta = collect_metadata(None, file_path, RULES_PATH, FORMAT, extractor)
capabilities, counts = find_capabilities(rulesSet, extractor, disable_progress=True)

file = open(join(self.wd.local, "capa.txt"), "w")
file.write(dumps(convert_capabilities_to_result_document(meta, rulesSet, capabilities)))
file.close()
```

**Expected behavior:**

Should write result to file

**Actual behavior:**

```
Traceback (most recent call last):
....
  File "/home/me/PycharmProjects/project/modules/file/capa_module.py", line 44, in capa
    file.write(dumps(convert_capabilities_to_result_document(meta, rulesSet, capabilities)))
  File "/home/me/PycharmProjects/project/venv/lib64/python3.9/site-packages/capa/render/__init__.py", line 212, in convert_capabilities_to_result_document
    "matches": {
  File "/home/me/PycharmProjects/project/venv/lib64/python3.9/site-packages/capa/render/__init__.py", line 213, in <dictcomp>
    addr: convert_match_to_result_document(rules, capabilities, match) for (addr, match) in matches
  File "/home/me/PycharmProjects/project/venv/lib64/python3.9/site-packages/capa/render/__init__.py", line 116, in convert_match_to_result_document
    "children": [convert_match_to_result_document(rules, capabilities, child) for child in result.children],
  File "/home/me/PycharmProjects/project/venv/lib64/python3.9/site-packages/capa/render/__init__.py", line 116, in <listcomp>
    "children": [convert_match_to_result_document(rules, capabilities, child) for child in result.children],
  File "/home/me/PycharmProjects/project/venv/lib64/python3.9/site-packages/capa/render/__init__.py", line 145, in convert_match_to_result_document
    rule = rules[rule_name]
  File "/home/me/PycharmProjects/project/venv/lib64/python3.9/site-packages/capa/rules.py", line 882, in __getitem__
    return self.rules[rulename]
KeyError: 'anti-analysis/packer'
```

### Versions

```
flare-capa: 1.6.3
capa-rules version: a207fbba0a7c4f82a8c8c514e878523ed7a85a49
viv-utils: 0.6.0
vivisect: 1.0.1
vivisect-vstruct-wb: 1.0.3
```

### Additional Information

Same file with capa from same VENV with same capa-rules

`capa -b vivisect -r <rules> <PE file>`

```
loading : 100%|████████████████████████████████████████████████████████████████████| 579/579 [00:00<00:00, 1771.32     rules/s]
..  analyzing programWARNING:viv_utils:vivisect version mismatch! wanted: 1.0.1, found: 1.0.0
matching: 100%|██████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 12.20 functions/s]
WARNING:capa:--------------------------------------------------------------------------------
WARNING:capa: This sample appears to be packed.
WARNING:capa: 
WARNING:capa: Packed samples have often been obfuscated to hide their logic.
WARNING:capa: capa cannot handle obfuscation well. This means the results may be misleading or incomplete.
WARNING:capa: If possible, you should try to unpack this input file before analyzing it with capa.
WARNING:capa: 
WARNING:capa: Use -v or -vv if you really want to see the capabilities identified by capa.
WARNING:capa:--------------------------------------------------------------------------------
```
I don't know why the version warning pops out, but it could be a clue!

I'm ready to provide that file but I don't think it's a good idea to past it here even I'm able to.
https://www.virustotal.com/gui/file/9ec96e0facf95d1a08d4761aff436dac8318abd008c7284a4a22347069e8284d/details

**Comment by mr-tz** [comment]
I think this stems from some checks we've added around file limitations.

Can you see if either of these fixes it?
* use capa-rules version v1.6.3: https://github.com/fireeye/capa-rules/commit/93ea28dd325c2db5e080272063c4dc12276c49cd
  * or remove/disable `rules/internal` as I think this issue stems from there
* use capa master (with according updates)

**Comment by BlastyCZ** [comment]
- use capa-rules version v1.6.1 - same error
- remove/disable rules/internal - well I don't know how to do that, did you mean remove folder from rules?
- use capa master (with according updates) - it works but it isn't good solution for me because it breaks dependencies

**Comment by mr-tz** [comment]
re: the 2nd suggestion, yes, remove the directory `rules/internal`

1) runs for me

```python
import sys

from capa.main import get_rules, get_extractor, collect_metadata, find_capabilities, BACKEND_VIV
from capa.render import render_json
from capa.rules import RuleSet

file_path = sys.argv[1]
rules = get_rules("rules", disable_progress=True)
rulesSet = RuleSet(rules)
extractor = get_extractor(file_path, "pe", BACKEND_VIV, disable_progress=True)
meta = collect_metadata(None, file_path, "rules", "pe", extractor)
capabilities, counts = find_capabilities(rulesSet, extractor, disable_progress=True)

file = open("capa.txt", "w")
file.write(render_json(meta, rulesSet, capabilities))
file.close()
```

```
capa
$ git reflog -n 1
c547519
rules
$ git reflog -n 1
93ea28d
```

**Comment by williballenthin** [comment]
ah, that's interesting that the addition of the internal rules is causing exceptions here. there was a related bug fixed in #608 (i think) and by fixing that i definitely didn't realize that adding rules could be a breaking change. i'm sorry you hit this error and its certainly not something we expected our users to deal with.

**Comment by BlastyCZ** [comment]
> re: the 2nd suggestion, yes, remove the directory `rules/internal`

It works in version 1.6.1

> 
>     1. runs for me
> 
> 
> ```python
> import sys
> 
> from capa.main import get_rules, get_extractor, collect_metadata, find_capabilities, BACKEND_VIV
> from capa.render import render_json
> from capa.rules import RuleSet
> 
> file_path = sys.argv[1]
> rules = get_rules("rules", disable_progress=True)
> rulesSet = RuleSet(rules)
> extractor = get_extractor(file_path, "pe", BACKEND_VIV, disable_progress=True)
> meta = collect_metadata(None, file_path, "rules", "pe", extractor)
> capabilities, counts = find_capabilities(rulesSet, extractor, disable_progress=True)
> 
> file = open("capa.txt", "w")
> file.write(render_json(meta, rulesSet, capabilities))
> file.close()
> ```
Same exception in version 1.6.1

Version from github (master) missing `render_json` in `capa.render` I wasn't able to find that function.

> ```
> capa
> $ git reflog -n 1
> c547519
> rules
> $ git reflog -n 1
> 93ea28d
> ```

capa
933789d (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: clone: from https://github.com/fireeye/capa

rules
a207fbb (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: pull -v origin: Fast-forward

**Comment by mr-tz** [comment]
The above script should work for the referenced capa commits. For master a few modifications are needed, I think.

https://github.com/fireeye/capa/blob/933789d02be12d1ed80fe6d93750555f54992423/capa/render/json.py#L28-L33

**Comment by mr-tz** [comment]
So, to clarify, you want to use `flare-capa` via pip (v1.6.3)? Using that with rules https://github.com/fireeye/capa-rules/tree/v1.6.1 does result in an error?

**Comment by BlastyCZ** [comment]
No I want to use version 1.6.1 via pip. First message contains version 1.6.3 just because I tried newest version from pip.
I must admit that I haven't notice there are tags for capa version - https://github.com/fireeye/capa-rules/tree/v1.6.1 works fine.
I thought using the latest version (master) would be better - becasuse of new rules, but I didn't realize it might not be backward compatible.

**Comment by BlastyCZ** [comment]
Actually I don't know if this is intended use (I mean using specific rules for specific capa version) or it is a bug?

**Comment by mr-tz** [comment]
Gotcha. Unfortunately, we cannot always guarantee backwards compatibility for all rules (as you've encountered here 😉).
Ideally, we can make this clearer in the documentation and code moving forward.

**Comment by BlastyCZ** [comment]
Got it!
