### ISSUE TITLE
SMDA doesn't correctly extract function names from ELF binaries

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#725]
![image](https://user-images.githubusercontent.com/156560/129101884-b99c6d5e-c718-4709-ac1e-a8faccc03773.png)

related to #699 ELF support

**Comment by williballenthin** [comment]
![image](https://user-images.githubusercontent.com/156560/129752412-5a1f679f-c8b8-49ab-954a-0f46a46c1b76.png)
![image](https://user-images.githubusercontent.com/156560/129752458-e6dc7325-4beb-4967-bc87-19926e299d9f.png)
![image](https://user-images.githubusercontent.com/156560/129752517-5124c7f4-e555-421f-9104-4562d03117ef.png)

**Comment by williballenthin** [comment]
SMDA does not consider `_open` an "API Thunk"
https://github.com/fireeye/capa/blob/dfe2dbea6dff32acd97becd176a99fbc3c16a255/capa/features/extractors/smda/insn.py#L55

![image](https://user-images.githubusercontent.com/156560/129754053-c7438524-7e12-4f30-bd60-228e0afabca3.png)

**Comment by williballenthin** [comment]
apirefs doesn't include the GOT entry for `open`:

![image](https://user-images.githubusercontent.com/156560/129754343-2a2d3d1e-1ede-4e45-9e09-821d2bfcc15a.png)

**Comment by williballenthin** [comment]
the ElfSymbolProvider does recognize the GOT entry:

![image](https://user-images.githubusercontent.com/156560/129757136-0bc667d6-762f-4328-ae1c-9ad80412a427.png)

**Comment by williballenthin** [comment]
ahhh, but the ElfSymbolResolver is a symbol resolver not an API resolver. so in `IntelDisassembler.resolveApi` the provider cannot recognize `open`.

**Comment by williballenthin** [comment]
PR in https://github.com/danielplohmann/smda/pull/24

**Comment by danielplohmann** [comment]
Thanks a lot again for the improvements, they are now available in the just published smda-1.6.0!
