### ISSUE TITLE
[TIP] Use of CAPA in the corporate world.

### ISSUE THREAD

**Issue by johnk3r** [fireeye/capa#782]
Hello, I'm going back to the project after some time. A lot of good things happened, huh...

I would like to take the use of the CAPA as a RE support and maturation tool to my team. I would like to know if you use or have already thought about using CAPA in an RE pipeline, some automation/abstraction or something like that. Even integration with other Fireeye products.

Tk

**Comment by johnk3r** [comment]
Hello, I'm going back to the project after some time. A lot of good things happened, huh...

I would like to take the use of the CAPA as a RE support and maturation tool to my team. I would like to know if you use or have already thought about using CAPA in an RE pipeline, some automation/abstraction or something like that. Even integration with other Fireeye products.

Tk

**Comment by mr-tz** [comment]
Welcome back 😄  That sounds like a great idea. We're definitely using capa in our workflow every day.

As far as integrations go checkout some of the open-source projects that already use capa like CAPE (https://github.com/kevoreilly/CAPEv2), https://github.com/accidentalrebel/mbcscan, and https://github.com/sgtdede/pe-checks.

**Comment by johnk3r** [comment]
Tk man.
